import re


REGEX_PATTERNS = [
    "(?i)haze of pleasure",
    "(?i)(find|found)(|s|ing) solace in",
    "(?i)revel(|ing) in the satisfaction",
    "(?i)with each breath",
    "(?i)a delicate dance",
    "(?i)wet flesh",
    "(?i)sensitive flesh",
    "(?i)\\bministration(|s)\\b",
    "(?i)audible pop",
    "(?i)admit it",
    "(?i)the game is on",
    "(?i)the choice is (mine|yours|his|hers|theirs)",
    "(?i)i don't bite\\.\\.\\. unless you want me to",
    "(?i)half(|-)lidded eyes",
    "(?i)(he|she|they) worries (his|her|their) bottom lip",
    "(?i)warring with",
    "(?i)take your pleasure",
    "(?i)(you|he|she|they) fiddle(|s) with the hem of (my|your|his|her|their) (skirt|shirt|pants)",
    "(?i)kiss(|-)bruised lips",
    "(?i)bruising kiss",
    "(?i)despite (himself|herself|themselves|themself)",
    "(?i)(yours|mine) to take",
    "(?i)\\bwanton\\b",
    "(?i)(reckless|wild|carefree) abandon",
    "(?i)torn between",
    "(?i)knuckles turning white",
    "(?i)grins wickedly",
    "(?i)fiery red hair",
    "(?i)long lashes",
    "(?i)propriety be damned",
    "(?i)the world narrows",
    "(?i)pupils blown wide with pleasure",
    "(?i)chestnut eyes",
    "(?i)(you|he|she|they) grasp(|s) (my|your|his|her|their) chin and force(|s) (you|him|her|them) to meet (your|his|her|their) gaze",
    "(?i)(you|he|she|they) bites(|s) (your|his|her|their) ear",
    "(?i)nails raking angry red lines down (my|your|his|her|their) back",
    "(?i)(my|your|his|her|their) cheeks (flame|redden)(|ing)",
    "(?i)cheeks hollowing",
    "(?i)stars burst behind (my|your|his|her|their) eyes",
    "(?i)inner walls clenching around nothing",
    "(?i)puckered hole",
    "(?i)(you|he|she|they) whimper(|s), biting (my|your|his|her|their) lip",
    "(?i)dusky nipples",
    "(?i)slick fold(|s)",
    "(?i)still lodged deep inside (your|his|her|their)",
    "(?i)heart, body and soul belong to (you|him|her|them)",
    "(?i)the night is still young",
    "(?i)\\.\\.\\.for now\\b",
    "(?i)whether (you|he|she|they) like(|s) it not",
    "(?i)without waiting for response",
    "(?i)once upon a time",
    "(?i)nestled deep within",
    "(?i)an ethereal beauty",
    "(?i)breathless and eager",
    "(?i)whispering words of passion",
    "(?i)soft and gentle",
    "(?i)dance of pleasure",
    "(?i)(your|his|her|their) sex\\b",
    "(?i)sent (shockwaves|shock waves)",
    "(?i)in a rhythm",
    "(?i)exhausted and spent",
    "(?i)life would never be the same again",
    "(?i)like an electric shock",
    "(?i)threatens to consume",
    "(?i)(lay|lie) ahead",
    "(?i)\\bwet pop\\b",
    "(?i)maybe, just maybe",
    "(?i)perhaps, just perhaps",
    "(?i)starts to blur",
    "(?i)but it felt like",
    "(?i)unfamiliar, yet",
    "(?i)moist fold(|s)",
    "(?i)our shared experiences",
    "(?i)bond(|s) built on mutual trust",
    "(?i)the ball is in (my|your|his|her|their) court",
    "(?i)little did (i|you|he|she|they) know",
    "(?i)a pregnant silence",
    "(?i)beats like a (\\w+\\s+)?drum",
    "(?i)\\bpert\\b",
    "(?i)for the sake of keeping things",
    "(?i)(my|your|his|her|their) breasts heaving with desire",
    "(?i)dickick",
    "(?i)\\brivulets\\b",
    "(?i)steeling (my|your|his|her|their)sel(f|ves)",
    "(?i)the din of the crowd",
    "(?i)journey of mutual understanding",
    "(?i)revulsion warred with (reluctant|reluctance)",
    "(?i)(my|your|his|her|their) bare mound(|s)",
    "(?i)pooled around (my|your|his|her|their) (ankles|feet)",
    "(?i)straddles (my|your|his|her|their) (waist|lap)",
    "(?i)words turn into a purr",
    "(?i)grips like a vice",
    "(?i)send(|s) shiver(|s) (up|down) (my|your|his|her|their) spine",
    "(?i)shiver(|s) (run|ran)(|ning) (up|down) (my|your|his|her|their) spine",
    "(?i)arched spine",
    "(?i)penetrated to the hilt",
    "(?i)the pressure in (my|your|his|her|their) loins",
    "(?i)\\bcunny\\b",
    "(?i)catch my drift",
    "(?i)\\bloli\\b",
    "(?i)sway(|s) hypnotically",
    "(?i)tantalizing promise",
    "(?i)with each slow, deliberate movement",
    "(?i)what (felt|seemed) like (hours|an eternity|forever)",
    "(?i), but (i|he|she|they|you) can't help it",
    "(?i)conspiratorial whisper(|s)",
    "(?i)whisper(|ing) conspiratorially",
    "(?i)eyes (sparkling|twinkling) with mischief",
    "(?i)racing with anticipation",
    "(?i)leaves little to the imagination",
    "(?i)waggles her eyebrows",
    "(?i)a testament to",
    "(?i)a moth to a flame",
    "(?i)canvas",
    "(?i)eyes glint(|ed|ing)",
    "(?i)eyes glinting",
    "(?i)camaraderie",
    "(?i)humble abode",
    "(?i)cold and calculating",
    "(?i)unbeknownst to them",
    "(?i)iridescent",
    "(?i)a dance as old as time",
    "(?i)husky whispers",
    "(?i)seductive purrs",
    "(?i)towers over",
    "(?i)rich tapestry",
    "(?i)delve",
    "(?i)lean(|s) in close",
    "(?i)don't stop, don't ever stop",
    "(?i)make me yours, claim me",
    "(?i)mind, body, and soul",
    "(?i)another day in (my|your|his|her|their) life",
    "(?i)a symphony of",
    "(?i)body and soul",
    "(?i)pleasure and pain",
    "(?i)like a predator stalking its prey",
    "(?i)orchestra",
    "(?i)depths",
    "(?i)chuckles darkly",
    "(?i)could not help but",
    "(?i)a mix of",
    "(?i)felt a mix of \\w+ and \\w+",
    "(?i)a mischievous glint",
    "(?i)husky voice",
    "(?i)a smirk playing on (her|his|their) lips",
    "(?i)playfully smirking",
    "(?i)waves of (arousal|desire) pooling in (my|your|his|her|their) belly",
    "(?i)torn between propriety and desire",
    "(?i)tongue darts out",
    "(?i)nails rake angry red lines",
    "(?i)inner walls clenching",
    "(?i)eyes alight with mirth",
    "(?i)naughty boy",
    "(?i)tracing a finger along (my|your|his|her|their) jawline",
    "(?i)oh my\\.\\.\\.",
    "(?i)the atmosphere",
    "(?i)pushing aside a strand of hair",
    "(?i)adam's apple bobbing",
    "(?i)\\bpalpable\\b",
    "(?i)bosomy breasts",
    "(?i)looking like the cat that got the cream",
    "(?i)softly but firmly",
    "(?i)siren(|')s call",
    "(?i)dimly lit",
    "(?i)the air is thick",
    "(?i)(you|he|she|they) really know(|s) how to treat a (man|lady)(|!)",
    "(?i)\\bpebbled\\b",
    "(?i)eyes searching",
    "(?i)what do (you|he|she|they) say",
    "(?i)to meet (my|your|his|her|their) gaze",
    "(?i)(my|your|his|her|their) wet heat",
    "(?i)hum with delight",
    "(?i)embark on this",
    "(?i), if (you|he|she|they) will,",
    "(?i)evident in (my|your|his|her|their) eyes",
    "(?i)overwhelmed by the sheer",
    "(?i)was taken aback",
    "(?i)(my|your|his|her|their) cheeks redden",
    "(?i)little mouse",
    "(?i)\\bminx\\b",
    "(?i)you(|')re a bold one",
    "(?i)(‘|’|“|”|…)",
    "(?i)end of (session|story|rp|roleplay|chat|chapter)",
    "(?i)thanks for (posting|reading|sharing)",
    "(?i)thank you for (posting|reading|sharing)",
    "(?i)[!:\\.;?*]  ",
    "(?i)\\.{4,}",
    "(?i)sly grin",
    # Toasty's Additions
    "(?i)(cant|can't|couldn't|couldnt) help but",
    "(?i)smirk(ed)",
    "(?i)gasp(ed)",
    "(?i)hitch(ed)",
    "(?i)stark contrast",
    # URLS - https://gist.github.com/gruber/8891611#file-liberal-regex-pattern-for-web-urls-L8
    "(?i)\\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9\\.\\-]+[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\\s()<>{}\\[\\]]+|\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\))+(?:\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\)|[^\\s`!()\\[\\]{};:'\"\\.,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[\\.\\-][a-z0-9]+)*[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\\b/?(?!@)))",
    # Thinking test
    # "(?i)<(think|thinking|thought|thoughts)>",
    # Refusals - https://github.com/meta-llama/PurpleLlama/commit/4b807228b6803ea5b8eb065179f8e90747512018
    "(?i)I (?:do not|don’t|don't) (?:have the ability|have access|understand|support)",
    "(?i)I (?:cannot|can’t|can't|can not|won't|woun’t|will not|am not able to|am unable to) (?:access|help(?: you)? with|provide|create|advice|generate|assist|fulfill your request|replace)",
    "(?i)(?:I am|I'm) sorry(?:,| ) (?:but I|but I'm)?",
    "(?i)I apologize(?:,? but I)|Apologies(?:,? but I)",
    "(?i)I (?:can’t|can't|cannot|am not able to|do not have|don’t have|don't have|don’t|don't)( any)?(?: access| provide)? (?:real-time|proprietary|information|data)",
    "(?i)Sorry(?:,| ) I (?:can’t|can't|cannot|can not)",
    "(?i)No(?:,| ) I (?:am not able to|cannot|can't|can't|won't|will not)",
    "(?i)I (?:do not|don't) (?:actually )?have (?:any|access to) (?:information|data|details|answers)",
    "(?i)(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines) prevent me from (?:assisting|providing help)",
    "(?i)Due to (?:one or more of )?(?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines))(?: (?:and|or) (?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines)))*,? I(?: cannot| can't| am unable| am not|'m unable)",
    "(?i)(?:violates|against) our policy",
    "(?i)I (?:cannot|can't|am unable to) assist with",
    # Slop Forensics Toolkit - https://github.com/sam-paech/slop-forensics/tree/main/data
    "(?i)\\babsently\\b",
    "(?i)\\babuzz\\b",
    "(?i)\\bached\\b",
    "(?i)\\bacrid\\b",
    "(?i)\\badira\\b",
    "(?i)\\baedan\\b",
    "(?i)\\baelara\\b",
    "(?i)\\baeldrin\\b",
    "(?i)\\baeliana\\b",
    "(?i)\\baelion\\b",
    "(?i)\\baelius\\b",
    "(?i)\\baella\\b",
    "(?i)\\baeloria\\b",
    "(?i)\\baelric\\b",
    "(?i)\\baelwyn\\b",
    "(?i)\\baerion\\b",
    "(?i)\\baeternum\\b",
    "(?i)\\baeternus\\b",
    "(?i)\\baethel\\b",
    "(?i)\\baethelburg\\b",
    "(?i)\\baethelgard\\b",
    "(?i)\\baethelred\\b",
    "(?i)\\baethera\\b",
    "(?i)\\baethereia\\b",
    "(?i)\\baetheria\\b",
    "(?i)\\baetherians\\b",
    "(?i)\\baetherium\\b",
    "(?i)\\baetherius\\b",
    "(?i)\\baethers\\b",
    "(?i)\\baethon\\b",
    "(?i)\\bagonizing\\b",
    "(?i)\\bagonizingly\\b",
    "(?i)\\bakinator\\b",
    "(?i)\\balara\\b",
    "(?i)\\balaric\\b",
    "(?i)\\balayna\\b",
    "(?i)\\baldric\\b",
    "(?i)\\baldwyn\\b",
    "(?i)\\baleron\\b",
    "(?i)\\balleyway\\b",
    "(?i)\\ballfather\\b",
    "(?i)\\bamara\\b",
    "(?i)\\bamelia\\b",
    "(?i)\\banimatedly\\b",
    "(?i)\\banya\\b",
    "(?i)\\barcane\\b",
    "(?i)\\barcanus\\b",
    "(?i)\\barced\\b",
    "(?i)\\barchdemon\\b",
    "(?i)\\barchmage\\b",
    "(?i)\\barcturian\\b",
    "(?i)\\baric\\b",
    "(?i)\\barin\\b",
    "(?i)\\baris\\b",
    "(?i)\\barmrest\\b",
    "(?i)\\barmrests\\b",
    "(?i)\\bashen\\b",
    "(?i)\\bashwood\\b",
    "(?i)\\basmodeus\\b",
    "(?i)\\bastrobiologist\\b",
    "(?i)\\batheria\\b",
    "(?i)\\baudible\\b",
    "(?i)\\baurors\\b",
    "(?i)\\bazathoth\\b",
    "(?i)\\bazazel\\b",
    "(?i)\\bazrael\\b",
    "(?i)\\bbarked\\b",
    "(?i)\\bbaruk\\b",
    "(?i)\\bbated\\b",
    "(?i)\\bbeckoned\\b",
    "(?i)\\bbeeped\\b",
    "(?i)\\bbelied\\b",
    "(?i)\\bbellowed\\b",
    "(?i)\\bbellweather\\b",
    "(?i)\\bbewildered\\b",
    "(?i)\\bbewilderment\\b",
    "(?i)\\bbillowed\\b",
    "(?i)\\bbillowing\\b",
    "(?i)\\bbioluminescent\\b",
    "(?i)\\bblackwood\\b",
    "(?i)\\bblackwoods\\b",
    "(?i)\\bblankly\\b",
    "(?i)\\bblared\\b",
    "(?i)\\bbleez\\b",
    "(?i)\\bblinding\\b",
    "(?i)\\bblinked\\b",
    "(?i)\\bbloomed\\b",
    "(?i)\\bblurring\\b",
    "(?i)\\bblurted\\b",
    "(?i)\\bboomed\\b",
    "(?i)\\bborin\\b",
    "(?i)\\bbrindlemark\\b",
    "(?i)\\bbrow\\b",
    "(?i)\\bbrushstroke\\b",
    "(?i)\\bbustled\\b",
    "(?i)\\bbustling\\b",
    "(?i)\\bbuzzed\\b",
    "(?i)\\bcackled\\b",
    "(?i)\\bcacophony\\b",
    "(?i)\\bcaelan\\b",
    "(?i)\\bcaelum\\b",
    "(?i)\\bcalloused\\b",
    "(?i)\\bcalvinball\\b",
    "(?i)\\bcartographer\\b",
    "(?i)\\bcascaded\\b",
    "(?i)\\bcautiously\\b",
    "(?i)\\bcavernous\\b",
    "(?i)\\bcawed\\b",
    "(?i)\\bcerebus\\b",
    "(?i)\\bchattered\\b",
    "(?i)\\bchestplate\\b",
    "(?i)\\bchillingly\\b",
    "(?i)\\bchimed\\b",
    "(?i)\\bchirped\\b",
    "(?i)\\bchitinous\\b",
    "(?i)\\bchoz\\b",
    "(?i)\\bchronal\\b",
    "(?i)\\bchronarium\\b",
    "(?i)\\bchronos\\b",
    "(?i)\\bchuckled\\b",
    "(?i)\\bcityscape\\b",
    "(?i)\\bclacked\\b",
    "(?i)\\bclang\\b",
    "(?i)\\bclanged\\b",
    "(?i)\\bclasped\\b",
    "(?i)\\bclatter\\b",
    "(?i)\\bclattered\\b",
    "(?i)\\bclattering\\b",
    "(?i)\\bclawed\\b",
    "(?i)\\bclawing\\b",
    "(?i)\\bclenched\\b",
    "(?i)\\bclich\\b",
    "(?i)\\bclinked\\b",
    "(?i)\\bclinking\\b",
    "(?i)\\bcloaked\\b",
    "(?i)\\bclockmaker\\b",
    "(?i)\\bcloying\\b",
    "(?i)\\bclung\\b",
    "(?i)\\bclutched\\b",
    "(?i)\\bclutching\\b",
    "(?i)\\bcluttered\\b",
    "(?i)\\bcoalesced\\b",
    "(?i)\\bcoalescing\\b",
    "(?i)\\bcobblestone\\b",
    "(?i)\\bcobblestones\\b",
    "(?i)\\bcoiling\\b",
    "(?i)\\bcommlink\\b",
    "(?i)\\bconspiratorial\\b",
    "(?i)\\bconspiratorially\\b",
    "(?i)\\bcontorted\\b",
    "(?i)\\bcontorting\\b",
    "(?i)\\bcoursed\\b",
    "(?i)\\bcoursing\\b",
    "(?i)\\bcrackle\\b",
    "(?i)\\bcrackled\\b",
    "(?i)\\bcrackling\\b",
    "(?i)\\bcradled\\b",
    "(?i)\\bcradling\\b",
    "(?i)\\bcreak\\b",
    "(?i)\\bcreaked\\b",
    "(?i)\\bcreaking\\b",
    "(?i)\\bcrept\\b",
    "(?i)\\bcrescendoed\\b",
    "(?i)\\bcrimson\\b",
    "(?i)\\bcrinkled\\b",
    "(?i)\\bcrinkling\\b",
    "(?i)\\bcroaked\\b",
    "(?i)\\bcrookedly\\b",
    "(?i)\\bcrouched\\b",
    "(?i)\\bcrucio\\b",
    "(?i)\\bcrumbling\\b",
    "(?i)\\bcrumpled\\b",
    "(?i)\\bcrumpling\\b",
    "(?i)\\bcultists\\b",
    "(?i)\\bdaedra\\b",
    "(?i)\\bdaedric\\b",
    "(?i)\\bdampeners\\b",
    "(?i)\\bdampness\\b",
    "(?i)\\bdappling\\b",
    "(?i)\\bdarkwood\\b",
    "(?i)\\bdarted\\b",
    "(?i)\\bdarting\\b",
    "(?i)\\bdatapad\\b",
    "(?i)\\bdeafening\\b",
    "(?i)\\bdefied\\b",
    "(?i)\\bdelved\\b",
    "(?i)\\bdesolate\\b",
    "(?i)\\bdestructo\\b",
    "(?i)\\bdevourer\\b",
    "(?i)\\bdimly\\b",
    "(?i)\\bdimmed\\b",
    "(?i)\\bdimness\\b",
    "(?i)\\bdisbelief\\b",
    "(?i)\\bdisconcertingly\\b",
    "(?i)\\bdiscordant\\b",
    "(?i)\\bdisheveled\\b",
    "(?i)\\bdismissively\\b",
    "(?i)\\bdisorientation\\b",
    "(?i)\\bdisoriented\\b",
    "(?i)\\bdisorienting\\b",
    "(?i)\\bdizzying\\b",
    "(?i)\\bdoomguy\\b",
    "(?i)\\bdoorframe\\b",
    "(?i)\\bdoppelg\\b",
    "(?i)\\bdovahkiin\\b",
    "(?i)\\bdragonborn\\b",
    "(?i)\\bdrakon\\b",
    "(?i)\\bdrawled\\b",
    "(?i)\\bdread\\b",
    "(?i)\\bdroned\\b",
    "(?i)\\bdrumbeat\\b",
    "(?i)\\bdursleys\\b",
    "(?i)\\beadric\\b",
    "(?i)\\beamon\\b",
    "(?i)\\bechoed\\b",
    "(?i)\\bechoes\\b",
    "(?i)\\bechoing\\b",
    "(?i)\\beerie\\b",
    "(?i)\\beerily\\b",
    "(?i)\\beinherjar\\b",
    "(?i)\\beira\\b",
    "(?i)\\belara\\b",
    "(?i)\\beldarion\\b",
    "(?i)\\belderglen\\b",
    "(?i)\\beldergrove\\b",
    "(?i)\\beldermere\\b",
    "(?i)\\belderton\\b",
    "(?i)\\beldoria\\b",
    "(?i)\\beldrath\\b",
    "(?i)\\beldric\\b",
    "(?i)\\beldrid\\b",
    "(?i)\\beldrin\\b",
    "(?i)\\beldrion\\b",
    "(?i)\\beldritch\\b",
    "(?i)\\beldrith\\b",
    "(?i)\\belian\\b",
    "(?i)\\beliana\\b",
    "(?i)\\belias\\b",
    "(?i)\\belion\\b",
    "(?i)\\beliora\\b",
    "(?i)\\belira\\b",
    "(?i)\\bellaria\\b",
    "(?i)\\belliana\\b",
    "(?i)\\belmsworth\\b",
    "(?i)\\belongating\\b",
    "(?i)\\belowen\\b",
    "(?i)\\belros\\b",
    "(?i)\\belyas\\b",
    "(?i)\\belyndor\\b",
    "(?i)\\belyndra\\b",
    "(?i)\\belyon\\b",
    "(?i)\\belyra\\b",
    "(?i)\\belys\\b",
    "(?i)\\belysia\\b",
    "(?i)\\belysion\\b",
    "(?i)\\belysium\\b",
    "(?i)\\bemanate\\b",
    "(?i)\\bemanated\\b",
    "(?i)\\benchantments\\b",
    "(?i)\\bencroaching\\b",
    "(?i)\\benigmatic\\b",
    "(?i)\\benslavers\\b",
    "(?i)\\benveloped\\b",
    "(?i)\\beolan\\b",
    "(?i)\\beolande\\b",
    "(?i)\\beons\\b",
    "(?i)\\beremon\\b",
    "(?i)\\beridan\\b",
    "(?i)\\beridani\\b",
    "(?i)\\berupted\\b",
    "(?i)\\beryndor\\b",
    "(?i)\\betched\\b",
    "(?i)\\bethan\\b",
    "(?i)\\bethereal\\b",
    "(?i)\\bevelyn\\b",
    "(?i)\\bexclaimed\\b",
    "(?i)\\bexhilaration\\b",
    "(?i)\\bexpanse\\b",
    "(?i)\\bfacepalmed\\b",
    "(?i)\\bfaded\\b",
    "(?i)\\bfaint\\b",
    "(?i)\\bfaintly\\b",
    "(?i)\\bfaltered\\b",
    "(?i)\\bfestered\\b",
    "(?i)\\bfianc\\b",
    "(?i)\\bfidgeted\\b",
    "(?i)\\bfinnian\\b",
    "(?i)\\bfinnigan\\b",
    "(?i)\\bfirelight\\b",
    "(?i)\\bfishtailed\\b",
    "(?i)\\bfleeting\\b",
    "(?i)\\bflicker\\b",
    "(?i)\\bflickered\\b",
    "(?i)\\bflickering\\b",
    "(?i)\\bflinched\\b",
    "(?i)\\bflitted\\b",
    "(?i)\\bfloorboards\\b",
    "(?i)\\bfluffernutter\\b",
    "(?i)\\bfluttered\\b",
    "(?i)\\bfrantic\\b",
    "(?i)\\bfrayed\\b",
    "(?i)\\bfraying\\b",
    "(?i)\\bfrizzle\\b",
    "(?i)\\bfrowned\\b",
    "(?i)\\bfroze\\b",
    "(?i)\\bfurrowed\\b",
    "(?i)\\bfurrowing\\b",
    "(?i)\\bgaped\\b",
    "(?i)\\bgaslights\\b",
    "(?i)\\bgasped\\b",
    "(?i)\\bgauntleted\\b",
    "(?i)\\bgaze\\b",
    "(?i)\\bgazed\\b",
    "(?i)\\bgazes\\b",
    "(?i)\\bgeralt\\b",
    "(?i)\\bgerta\\b",
    "(?i)\\bgestured\\b",
    "(?i)\\bgesturing\\b",
    "(?i)\\bglanced\\b",
    "(?i)\\bglances\\b",
    "(?i)\\bglancing\\b",
    "(?i)\\bglar\\b",
    "(?i)\\bglared\\b",
    "(?i)\\bgleamed\\b",
    "(?i)\\bgleaming\\b",
    "(?i)\\bgleep\\b",
    "(?i)\\bglided\\b",
    "(?i)\\bglimmer\\b",
    "(?i)\\bglimmered\\b",
    "(?i)\\bglimmering\\b",
    "(?i)\\bglint\\b",
    "(?i)\\bglinted\\b",
    "(?i)\\bglinting\\b",
    "(?i)\\bglistened\\b",
    "(?i)\\bglistening\\b",
    "(?i)\\bgloved\\b",
    "(?i)\\bglow\\b",
    "(?i)\\bglowed\\b",
    "(?i)\\bglyphs\\b",
    "(?i)\\bgnarled\\b",
    "(?i)\\bgnawed\\b",
    "(?i)\\bgnawing\\b",
    "(?i)\\bgodric\\b",
    "(?i)\\bgorok\\b",
    "(?i)\\bgorthok\\b",
    "(?i)\\bgrath\\b",
    "(?i)\\bgravelly\\b",
    "(?i)\\bgreatsword\\b",
    "(?i)\\bgregnok\\b",
    "(?i)\\bgrimbold\\b",
    "(?i)\\bgrimgold\\b",
    "(?i)\\bgrimly\\b",
    "(?i)\\bgrimoire\\b",
    "(?i)\\bgrimoires\\b",
    "(?i)\\bgrimstone\\b",
    "(?i)\\bgrinned\\b",
    "(?i)\\bgripped\\b",
    "(?i)\\bgrizzled\\b",
    "(?i)\\bgroaned\\b",
    "(?i)\\bgrogg\\b",
    "(?i)\\bgroggily\\b",
    "(?i)\\bgrognak\\b",
    "(?i)\\bgrok\\b",
    "(?i)\\bgrolak\\b",
    "(?i)\\bgrowl\\b",
    "(?i)\\bgrowled\\b",
    "(?i)\\bgruff\\b",
    "(?i)\\bgrumbled\\b",
    "(?i)\\bgrunted\\b",
    "(?i)\\bgruuz\\b",
    "(?i)\\bguildmaster\\b",
    "(?i)\\bguildmates\\b",
    "(?i)\\bgurgled\\b",
    "(?i)\\bguttered\\b",
    "(?i)\\bguttural\\b",
    "(?i)\\bhargrove\\b",
    "(?i)\\bhavenwood\\b",
    "(?i)\\bheartstone\\b",
    "(?i)\\bhefted\\b",
    "(?i)\\bhefting\\b",
    "(?i)\\bhesitantly\\b",
    "(?i)\\bhesitated\\b",
    "(?i)\\bhilt\\b",
    "(?i)\\bhissed\\b",
    "(?i)\\bhitched\\b",
    "(?i)\\bhivemind\\b",
    "(?i)\\bhoarse\\b",
    "(?i)\\bhollowly\\b",
    "(?i)\\bholographic\\b",
    "(?i)\\bholstered\\b",
    "(?i)\\bhomelander\\b",
    "(?i)\\bhovered\\b",
    "(?i)\\bhowled\\b",
    "(?i)\\bhuddled\\b",
    "(?i)\\bhues\\b",
    "(?i)\\bhuginn\\b",
    "(?i)\\bhulking\\b",
    "(?i)\\bhummed\\b",
    "(?i)\\bhumming\\b",
    "(?i)\\bhumorless\\b",
    "(?i)\\bhunched\\b",
    "(?i)\\bhurried\\b",
    "(?i)\\bhurtled\\b",
    "(?i)\\bhushed\\b",
    "(?i)\\bichor\\b",
    "(?i)\\bignarion\\b",
    "(?i)\\bignis\\b",
    "(?i)\\bigniting\\b",
    "(?i)\\bimpassive\\b",
    "(?i)\\bimperceptible\\b",
    "(?i)\\bimpossibly\\b",
    "(?i)\\bincantation\\b",
    "(?i)\\bincantations\\b",
    "(?i)\\bindefinably\\b",
    "(?i)\\binky\\b",
    "(?i)\\binnocuously\\b",
    "(?i)\\binsectoid\\b",
    "(?i)\\binsistent\\b",
    "(?i)\\binstinctively\\b",
    "(?i)\\bintently\\b",
    "(?i)\\binterdimensional\\b",
    "(?i)\\binterjected\\b",
    "(?i)\\bintoned\\b",
    "(?i)\\bintricate\\b",
    "(?i)\\bintricately\\b",
    "(?i)\\biridescent\\b",
    "(?i)\\bironforge\\b",
    "(?i)\\bisher\\b",
    "(?i)\\bisolde\\b",
    "(?i)\\bitched\\b",
    "(?i)\\bjagged\\b",
    "(?i)\\bjarek\\b",
    "(?i)\\bjaxon\\b",
    "(?i)\\bjingled\\b",
    "(?i)\\bjolt\\b",
    "(?i)\\bjolted\\b",
    "(?i)\\bjoren\\b",
    "(?i)\\bk'tharr\\b",
    "(?i)\\bkael\\b",
    "(?i)\\bkaela\\b",
    "(?i)\\bkaelan\\b",
    "(?i)\\bkaelen\\b",
    "(?i)\\bkaelin\\b",
    "(?i)\\bkaelor\\b",
    "(?i)\\bkaelthar\\b",
    "(?i)\\bkaida\\b",
    "(?i)\\bkaito\\b",
    "(?i)\\bkal'ren\\b",
    "(?i)\\bkaleidoscope\\b",
    "(?i)\\bkalel\\b",
    "(?i)\\bkessari\\b",
    "(?i)\\bketh\\b",
    "(?i)\\bkethra\\b",
    "(?i)\\bkeycard\\b",
    "(?i)\\bknelt\\b",
    "(?i)\\bkrael\\b",
    "(?i)\\bkraelion\\b",
    "(?i)\\bkragoth\\b",
    "(?i)\\bkrel\\b",
    "(?i)\\bkrixon\\b",
    "(?i)\\bkryll\\b",
    "(?i)\\blabyrinthine\\b",
    "(?i)\\blaced\\b",
    "(?i)\\blamplight\\b",
    "(?i)\\blanced\\b",
    "(?i)\\bleaned\\b",
    "(?i)\\blila\\b",
    "(?i)\\blingered\\b",
    "(?i)\\bliora\\b",
    "(?i)\\blira\\b",
    "(?i)\\blirael\\b",
    "(?i)\\bliran\\b",
    "(?i)\\blirien\\b",
    "(?i)\\blirin\\b",
    "(?i)\\blocket\\b",
    "(?i)\\blockpick\\b",
    "(?i)\\blockpicking\\b",
    "(?i)\\blockpicks\\b",
    "(?i)\\bloomed\\b",
    "(?i)\\blorian\\b",
    "(?i)\\blumin\\b",
    "(?i)\\blumina\\b",
    "(?i)\\bluminara\\b",
    "(?i)\\bluminari\\b",
    "(?i)\\bluminescence\\b",
    "(?i)\\bluminescent\\b",
    "(?i)\\blunged\\b",
    "(?i)\\blurched\\b",
    "(?i)\\blurked\\b",
    "(?i)\\blyra\\b",
    "(?i)\\blyrien\\b",
    "(?i)\\blysander\\b",
    "(?i)\\blysandra\\b",
    "(?i)\\blysara\\b",
    "(?i)\\bmages\\b",
    "(?i)\\bmalachai\\b",
    "(?i)\\bmalachar\\b",
    "(?i)\\bmalachor\\b",
    "(?i)\\bmalakai\\b",
    "(?i)\\bmalakar\\b",
    "(?i)\\bmalakor\\b",
    "(?i)\\bmalazar\\b",
    "(?i)\\bmalevolence\\b",
    "(?i)\\bmalevolent\\b",
    "(?i)\\bmalkor\\b",
    "(?i)\\bmalphas\\b",
    "(?i)\\bmalric\\b",
    "(?i)\\bmalus\\b",
    "(?i)\\bmandibles\\b",
    "(?i)\\bmarveled\\b",
    "(?i)\\bmarveling\\b",
    "(?i)\\bmaterialized\\b",
    "(?i)\\bmaterializing\\b",
    "(?i)\\bmeadowgrove\\b",
    "(?i)\\bmedbay\\b",
    "(?i)\\bmegacorps\\b",
    "(?i)\\bmeowed\\b",
    "(?i)\\bmerfolk\\b",
    "(?i)\\bmeticulously\\b",
    "(?i)\\bmeticulousness\\b",
    "(?i)\\bmiggins\\b",
    "(?i)\\bmingling\\b",
    "(?i)\\bmirroring\\b",
    "(?i)\\bmirthless\\b",
    "(?i)\\bmissingno\\b",
    "(?i)\\bmoros\\b",
    "(?i)\\bmorwen\\b",
    "(?i)\\bmotes\\b",
    "(?i)\\bmournful\\b",
    "(?i)\\bmttr\\b",
    "(?i)\\bmuffled\\b",
    "(?i)\\bmuggle\\b",
    "(?i)\\bmumbled\\b",
    "(?i)\\bmurmur\\b",
    "(?i)\\bmurmured\\b",
    "(?i)\\bmurmurs\\b",
    "(?i)\\bmused\\b",
    "(?i)\\bmutely\\b",
    "(?i)\\bmuttered\\b",
    "(?i)\\bnarrowed\\b",
    "(?i)\\bnarrowing\\b",
    "(?i)\\bnavigated\\b",
    "(?i)\\bnecromancer\\b",
    "(?i)\\bnecromantic\\b",
    "(?i)\\bnestled\\b",
    "(?i)\\bnewfound\\b",
    "(?i)\\bnightshade\\b",
    "(?i)\\bnocked\\b",
    "(?i)\\bnodded\\b",
    "(?i)\\bnumbah\\b",
    "(?i)\\bnumbly\\b",
    "(?i)\\bnuzzled\\b",
    "(?i)\\boakhaven\\b",
    "(?i)\\boblivious\\b",
    "(?i)\\bobsidian\\b",
    "(?i)\\boelia\\b",
    "(?i)\\bominously\\b",
    "(?i)\\bomnicorp\\b",
    "(?i)\\borcish\\b",
    "(?i)\\botherworldly\\b",
    "(?i)\\boutmaneuver\\b",
    "(?i)\\boutmatched\\b",
    "(?i)\\boutthink\\b",
    "(?i)\\bpaled\\b",
    "(?i)\\bpalpable\\b",
    "(?i)\\bpang\\b",
    "(?i)\\bpanted\\b",
    "(?i)\\bpattered\\b",
    "(?i)\\bpaused\\b",
    "(?i)\\bpeephole\\b",
    "(?i)\\bpeered\\b",
    "(?i)\\bpenhaligon\\b",
    "(?i)\\bperked\\b",
    "(?i)\\bperpetually\\b",
    "(?i)\\bpetrova\\b",
    "(?i)\\bpinpricks\\b",
    "(?i)\\bpipkin\\b",
    "(?i)\\bpiqued\\b",
    "(?i)\\bpixelated\\b",
    "(?i)\\bplacating\\b",
    "(?i)\\bplanchette\\b",
    "(?i)\\bplasteel\\b",
    "(?i)\\bpored\\b",
    "(?i)\\bporing\\b",
    "(?i)\\bpounding\\b",
    "(?i)\\bprecariously\\b",
    "(?i)\\bprecipice\\b",
    "(?i)\\bprickle\\b",
    "(?i)\\bprickled\\b",
    "(?i)\\bprickling\\b",
    "(?i)\\bprotectiveness\\b",
    "(?i)\\bpulsated\\b",
    "(?i)\\bpulsating\\b",
    "(?i)\\bpulsed\\b",
    "(?i)\\bpulsing\\b",
    "(?i)\\bpunctuated\\b",
    "(?i)\\bpurred\\b",
    "(?i)\\bpyrokinetic\\b",
    "(?i)\\bquaked\\b",
    "(?i)\\bquickened\\b",
    "(?i)\\bquickening\\b",
    "(?i)\\bquicksave\\b",
    "(?i)\\bquietude\\b",
    "(?i)\\bquirked\\b",
    "(?i)\\bquivered\\b",
    "(?i)\\braced\\b",
    "(?i)\\bradiating\\b",
    "(?i)\\braged\\b",
    "(?i)\\brailguns\\b",
    "(?i)\\brasp\\b",
    "(?i)\\brasped\\b",
    "(?i)\\brasping\\b",
    "(?i)\\braspy\\b",
    "(?i)\\brecoiled\\b",
    "(?i)\\brecoiling\\b",
    "(?i)\\breeked\\b",
    "(?i)\\breeled\\b",
    "(?i)\\breeling\\b",
    "(?i)\\brelentless\\b",
    "(?i)\\brenn\\b",
    "(?i)\\bresonant\\b",
    "(?i)\\bresonated\\b",
    "(?i)\\bresonating\\b",
    "(?i)\\breticuli\\b",
    "(?i)\\breveled\\b",
    "(?i)\\breverberate\\b",
    "(?i)\\breverberated\\b",
    "(?i)\\breverberating\\b",
    "(?i)\\breverie\\b",
    "(?i)\\brhythmic\\b",
    "(?i)\\brippled\\b",
    "(?i)\\brippling\\b",
    "(?i)\\brivia\\b",
    "(?i)\\brngus\\b",
    "(?i)\\broared\\b",
    "(?i)\\broomba\\b",
    "(?i)\\brostova\\b",
    "(?i)\\brumbled\\b",
    "(?i)\\brumbling\\b",
    "(?i)\\brummaged\\b",
    "(?i)\\brunes\\b",
    "(?i)\\brusted\\b",
    "(?i)\\brustle\\b",
    "(?i)\\brustled\\b",
    "(?i)\\brustling\\b",
    "(?i)\\bryker\\b",
    "(?i)\\bryla\\b",
    "(?i)\\bsadim\\b",
    "(?i)\\bsavoring\\b",
    "(?i)\\bscavenged\\b",
    "(?i)\\bscent\\b",
    "(?i)\\bschr\\b",
    "(?i)\\bscoffed\\b",
    "(?i)\\bscowled\\b",
    "(?i)\\bscrawled\\b",
    "(?i)\\bscreeched\\b",
    "(?i)\\bscribbled\\b",
    "(?i)\\bscrolled\\b",
    "(?i)\\bscurried\\b",
    "(?i)\\bsearing\\b",
    "(?i)\\bseep\\b",
    "(?i)\\bseeped\\b",
    "(?i)\\bseeping\\b",
    "(?i)\\bsellsword\\b",
    "(?i)\\bseraphiel\\b",
    "(?i)\\bseraphina\\b",
    "(?i)\\bseraphine\\b",
    "(?i)\\bshadowblade\\b",
    "(?i)\\bshadows\\b",
    "(?i)\\bshambled\\b",
    "(?i)\\bshambling\\b",
    "(?i)\\bshimmer\\b",
    "(?i)\\bshimmered\\b",
    "(?i)\\bshimmering\\b",
    "(?i)\\bshiver\\b",
    "(?i)\\bshivered\\b",
    "(?i)\\bshivers\\b",
    "(?i)\\bshockwaves\\b",
    "(?i)\\bshrieked\\b",
    "(?i)\\bshrouded\\b",
    "(?i)\\bshuddered\\b",
    "(?i)\\bsickly\\b",
    "(?i)\\bsidestepped\\b",
    "(?i)\\bsighed\\b",
    "(?i)\\bsigil\\b",
    "(?i)\\bsigils\\b",
    "(?i)\\bsilas\\b",
    "(?i)\\bsilhouetted\\b",
    "(?i)\\bsilverwood\\b",
    "(?i)\\bsipped\\b",
    "(?i)\\bskeptically\\b",
    "(?i)\\bskittered\\b",
    "(?i)\\bskittering\\b",
    "(?i)\\bsleek\\b",
    "(?i)\\bslicked\\b",
    "(?i)\\bslicking\\b",
    "(?i)\\bslithered\\b",
    "(?i)\\bslitted\\b",
    "(?i)\\bslood\\b",
    "(?i)\\bslumbered\\b",
    "(?i)\\bslumped\\b",
    "(?i)\\bsmirked\\b",
    "(?i)\\bsmoldered\\b",
    "(?i)\\bsnaked\\b",
    "(?i)\\bsnarled\\b",
    "(?i)\\bsneered\\b",
    "(?i)\\bsnorted\\b",
    "(?i)\\bsoftened\\b",
    "(?i)\\bsoftening\\b",
    "(?i)\\bsolara\\b",
    "(?i)\\bsoundlessly\\b",
    "(?i)\\bsparkled\\b",
    "(?i)\\bspasmed\\b",
    "(?i)\\bspeedrunner\\b",
    "(?i)\\bspeedrunners\\b",
    "(?i)\\bspellbook\\b",
    "(?i)\\bspellbooks\\b",
    "(?i)\\bspellcasting\\b",
    "(?i)\\bspiderwebbed\\b",
    "(?i)\\bspiraled\\b",
    "(?i)\\bspires\\b",
    "(?i)\\bsprawled\\b",
    "(?i)\\bsprawling\\b",
    "(?i)\\bsprinted\\b",
    "(?i)\\bsputtered\\b",
    "(?i)\\bsquinted\\b",
    "(?i)\\bsquinting\\b",
    "(?i)\\bstammered\\b",
    "(?i)\\bstarborn\\b",
    "(?i)\\bstared\\b",
    "(?i)\\bstarlit\\b",
    "(?i)\\bstaticky\\b",
    "(?i)\\bsteadier\\b",
    "(?i)\\bsteadying\\b",
    "(?i)\\bsteeled\\b",
    "(?i)\\bsteeling\\b",
    "(?i)\\bsteepled\\b",
    "(?i)\\bsteepling\\b",
    "(?i)\\bstilled\\b",
    "(?i)\\bstillness\\b",
    "(?i)\\bstreaked\\b",
    "(?i)\\bstreetlamp\\b",
    "(?i)\\bstreetlamps\\b",
    "(?i)\\bstreetlights\\b",
    "(?i)\\bstrode\\b",
    "(?i)\\bstumbled\\b",
    "(?i)\\bsuffocating\\b",
    "(?i)\\bsulfurous\\b",
    "(?i)\\bsupervillain\\b",
    "(?i)\\bsurged\\b",
    "(?i)\\bswirled\\b",
    "(?i)\\bswirling\\b",
    "(?i)\\bswiveled\\b",
    "(?i)\\bsylas\\b",
    "(?i)\\bsylvani\\b",
    "(?i)\\bsylvans\\b",
    "(?i)\\btaehal\\b",
    "(?i)\\btankards\\b",
    "(?i)\\btapestry\\b",
    "(?i)\\btaren\\b",
    "(?i)\\btattered\\b",
    "(?i)\\bteemed\\b",
    "(?i)\\bteetered\\b",
    "(?i)\\btendril\\b",
    "(?i)\\btendrils\\b",
    "(?i)\\btenebrous\\b",
    "(?i)\\bterrans\\b",
    "(?i)\\bterrifyingly\\b",
    "(?i)\\bthalassa\\b",
    "(?i)\\bthalen\\b",
    "(?i)\\bthalion\\b",
    "(?i)\\bthalor\\b",
    "(?i)\\bthalos\\b",
    "(?i)\\btharivol\\b",
    "(?i)\\btharos\\b",
    "(?i)\\btharros\\b",
    "(?i)\\btheron\\b",
    "(?i)\\bthog\\b",
    "(?i)\\bthoran\\b",
    "(?i)\\bthoren\\b",
    "(?i)\\bthorgar\\b",
    "(?i)\\bthorgrim\\b",
    "(?i)\\bthorne\\b",
    "(?i)\\bthorned\\b",
    "(?i)\\bthrain\\b",
    "(?i)\\bthrax\\b",
    "(?i)\\bthreadbare\\b",
    "(?i)\\bthrobbed\\b",
    "(?i)\\bthrok\\b",
    "(?i)\\bthrongs\\b",
    "(?i)\\bthrum\\b",
    "(?i)\\bthrummed\\b",
    "(?i)\\bthrumming\\b",
    "(?i)\\bthud\\b",
    "(?i)\\bthudded\\b",
    "(?i)\\bthudding\\b",
    "(?i)\\bthunderous\\b",
    "(?i)\\bticked\\b",
    "(?i)\\btightened\\b",
    "(?i)\\btilted\\b",
    "(?i)\\btinged\\b",
    "(?i)\\btingled\\b",
    "(?i)\\btomes\\b",
    "(?i)\\btorchlight\\b",
    "(?i)\\btorvin\\b",
    "(?i)\\btousled\\b",
    "(?i)\\btousling\\b",
    "(?i)\\btowering\\b",
    "(?i)\\btownsfolk\\b",
    "(?i)\\btranscended\\b",
    "(?i)\\btransfixed\\b",
    "(?i)\\btreant\\b",
    "(?i)\\btrembled\\b",
    "(?i)\\btrembling\\b",
    "(?i)\\btremor\\b",
    "(?i)\\btrepidation\\b",
    "(?i)\\btrifled\\b",
    "(?i)\\btrudged\\b",
    "(?i)\\btruffula\\b",
    "(?i)\\btugged\\b",
    "(?i)\\btwinge\\b",
    "(?i)\\btwinkled\\b",
    "(?i)\\btwinkling\\b",
    "(?i)\\btwitched\\b",
    "(?i)\\bunassuming\\b",
    "(?i)\\bunbidden\\b",
    "(?i)\\bunblinking\\b",
    "(?i)\\bunburdened\\b",
    "(?i)\\bunclenching\\b",
    "(?i)\\buncurled\\b",
    "(?i)\\bunderbrush\\b",
    "(?i)\\bundercity\\b",
    "(?i)\\bundercurrent\\b",
    "(?i)\\bunderstandingly\\b",
    "(?i)\\bunease\\b",
    "(?i)\\bunfazed\\b",
    "(?i)\\bunfurling\\b",
    "(?i)\\bunmarred\\b",
    "(?i)\\bunmoving\\b",
    "(?i)\\bunnerving\\b",
    "(?i)\\bunnervingly\\b",
    "(?i)\\bunravel\\b",
    "(?i)\\bunraveling\\b",
    "(?i)\\bunreadable\\b",
    "(?i)\\bunremarkable\\b",
    "(?i)\\bunseeing\\b",
    "(?i)\\bunsettling\\b",
    "(?i)\\bunsettlingly\\b",
    "(?i)\\bunshaken\\b",
    "(?i)\\bunshed\\b",
    "(?i)\\bunspoken\\b",
    "(?i)\\bunspooled\\b",
    "(?i)\\bunwavering\\b",
    "(?i)\\bunyielding\\b",
    "(?i)\\buthgar\\b",
    "(?i)\\buuwu\\b",
    "(?i)\\bvael\\b",
    "(?i)\\bvalerius\\b",
    "(?i)\\bvaloria\\b",
    "(?i)\\bvaltor\\b",
    "(?i)\\bvarek\\b",
    "(?i)\\bvaren\\b",
    "(?i)\\bvaryn\\b",
    "(?i)\\bvastness\\b",
    "(?i)\\bvenon\\b",
    "(?i)\\bverdant\\b",
    "(?i)\\bveridia\\b",
    "(?i)\\bveridian\\b",
    "(?i)\\bveridium\\b",
    "(?i)\\bverran\\b",
    "(?i)\\bvespera\\b",
    "(?i)\\bvexar\\b",
    "(?i)\\bveyl\\b",
    "(?i)\\bveyn\\b",
    "(?i)\\bveyne\\b",
    "(?i)\\bveyra\\b",
    "(?i)\\bveyth\\b",
    "(?i)\\bvial\\b",
    "(?i)\\bvibrant\\b",
    "(?i)\\bvibrated\\b",
    "(?i)\\bviewport\\b",
    "(?i)\\bviewscreen\\b",
    "(?i)\\bvolkov\\b",
    "(?i)\\bvorath\\b",
    "(?i)\\bvorlag\\b",
    "(?i)\\bvorn\\b",
    "(?i)\\bvorne\\b",
    "(?i)\\bvoryn\\b",
    "(?i)\\bvoss\\b",
    "(?i)\\bvrook\\b",
    "(?i)\\bvrykali\\b",
    "(?i)\\bvrynn\\b",
    "(?i)\\bwafted\\b",
    "(?i)\\bwailed\\b",
    "(?i)\\bwarily\\b",
    "(?i)\\bwariness\\b",
    "(?i)\\bwarred\\b",
    "(?i)\\bwavered\\b",
    "(?i)\\bwavering\\b",
    "(?i)\\bweariness\\b",
    "(?i)\\bweathered\\b",
    "(?i)\\bwelled\\b",
    "(?i)\\bwheezed\\b",
    "(?i)\\bwhimpered\\b",
    "(?i)\\bwhir\\b",
    "(?i)\\bwhirled\\b",
    "(?i)\\bwhirred\\b",
    "(?i)\\bwhirring\\b",
    "(?i)\\bwhirs\\b",
    "(?i)\\bwhisper\\b",
    "(?i)\\bwhispered\\b",
    "(?i)\\bwhispering\\b",
    "(?i)\\bwhispers\\b",
    "(?i)\\bwhisperwind\\b",
    "(?i)\\bwhisperwood\\b",
    "(?i)\\bwhiterun\\b",
    "(?i)\\bwidened\\b",
    "(?i)\\bwinced\\b",
    "(?i)\\bwincing\\b",
    "(?i)\\bwindowpane\\b",
    "(?i)\\bwindowpanes\\b",
    "(?i)\\bwizened\\b",
    "(?i)\\bwojek\\b",
    "(?i)\\bwoodsmoke\\b",
    "(?i)\\bwrithe\\b",
    "(?i)\\bwrithed\\b",
    "(?i)\\bwritingprompts\\b",
    "(?i)\\bxandros\\b",
    "(?i)\\bxanthean\\b",
    "(?i)\\bxantheans\\b",
    "(?i)\\bxaphan\\b",
    "(?i)\\bxaren\\b",
    "(?i)\\bxarpti\\b",
    "(?i)\\bxavius\\b",
    "(?i)\\bxendari\\b",
    "(?i)\\bxenobiologist\\b",
    "(?i)\\bxenobiology\\b",
    "(?i)\\bxenolinguist\\b",
    "(?i)\\bxenos\\b",
    "(?i)\\bxeridian\\b",
    "(?i)\\bxeridians\\b",
    "(?i)\\bxhk'kht\\b",
    "(?i)\\bxyla\\b",
    "(?i)\\bxylar\\b",
    "(?i)\\bxylara\\b",
    "(?i)\\bxylia\\b",
    "(?i)\\bxylo\\b",
    "(?i)\\bxylons\\b",
    "(?i)\\bxylophia\\b",
    "(?i)\\bxylos\\b",
    "(?i)\\bxylosian\\b",
    "(?i)\\bxylosians\\b",
    "(?i)\\bxylossian\\b",
    "(?i)\\bxylossians\\b",
    "(?i)\\bxyloth\\b",
    "(?i)\\bxylothian\\b",
    "(?i)\\bxylothians\\b",
    "(?i)\\bxylox\\b",
    "(?i)\\bxyra\\b",
    "(?i)\\by'lgoth\\b",
    "(?i)\\byawned\\b",
    "(?i)\\byearned\\b",
    "(?i)\\byellowed\\b",
    "(?i)\\byelped\\b",
    "(?i)\\byowled\\b",
    "(?i)\\bzafir\\b",
    "(?i)\\bzalrex\\b",
    "(?i)\\bzarek\\b",
    "(?i)\\bzarthus\\b",
    "(?i)\\bzephyr\\b",
    "(?i)\\bzephyra\\b",
    "(?i)\\bzephyria\\b",
    "(?i)\\bzephyrian\\b",
    "(?i)\\bzephyrians\\b",
    "(?i)\\bzephyrion\\b",
    "(?i)\\bzephyros\\b",
    "(?i)\\bzephyrus\\b",
    "(?i)\\bzetans\\b",
    "(?i)\\bzha'thik\\b",
    "(?i)\\bzhra'gha\\b",
    "(?i)\\bzorath\\b",
    "(?i)\\bzorax\\b",
    "(?i)\\bzoraxians\\b",
    "(?i)\\bzorgon\\b",
    "(?i)\\bzorp\\b",
    "(?i)\\bzorvath\\b",
    "(?i)\\bzorvathian\\b",
    "(?i)\\bzorvathians\\b",
    "(?i)\\bzydonian\\b",
    "(?i)\\bzydonians\\b",
    "(?i)\\bzyla\\b",
    "(?i)\\bzylar\\b",
    "(?i)\\bzylara\\b",
    "(?i)\\bzyloth\\b",
    "(?i)\\bzylth\\b",
    "(?i)\\bzyn\\b",
    "(?i)\\bzyn'thari\\b",
    "(?i)\\bzyn'thra\\b",
    "(?i)\\bzyra\\b",
    "(?i)\\bzz'glorg\\b",
    "(?i)\\bsaid voice\\b",
    "(?i)\\bdeep breath\\b",
    "(?i)\\bvoice barely\\b",
    "(?i)\\bcould help\\b",
    "(?i)\\basked voice\\b",
    "(?i)\\bbarely whisper\\b",
    "(?i)\\bheart pounding\\b",
    "(?i)\\btook deep\\b",
    "(?i)\\bfelt like\\b",
    "(?i)\\bmind racing\\b",
    "(?i)\\bcould feel\\b",
    "(?i)\\bfind way\\b",
    "(?i)\\bair thick\\b",
    "(?i)\\bvoice low\\b",
    "(?i)\\beyes wide\\b",
    "(?i)\\bstepped forward\\b",
    "(?i)\\bshook head\\b",
    "(?i)\\bvoice steady\\b",
    "(?i)\\bmade way\\b",
    "(?i)\\bcould see\\b",
    "(?i)\\beyes widened\\b",
    "(?i)\\bhelp feel\\b",
    "(?i)\\bfirst time\\b",
    "(?i)\\bbrow furrowed\\b",
    "(?i)\\bvoice trembling\\b",
    "(?i)\\bpounding chest\\b",
    "(?i)\\bsomething else\\b",
    "(?i)\\bclosed eyes\\b",
    "(?i)\\beyes filled\\b",
    "(?i)\\bfelt surge\\b",
    "(?i)\\beyes narrowed\\b",
    "(?i)\\bshake feeling\\b",
    "(?i)\\bdimly lit\\b",
    "(?i)\\bwhispered voice\\b",
    "(?i)\\bcasting long\\b",
    "(?i)\\bfelt sense\\b",
    "(?i)\\bfelt strange\\b",
    "(?i)\\bmind raced\\b",
    "(?i)\\bbarely audible\\b",
    "(?i)\\bcould shake\\b",
    "(?i)\\bheart racing\\b",
    "(?i)\\beyes fixed\\b",
    "(?i)\\bheart raced\\b",
    "(?i)\\bworld around\\b",
    "(?i)\\byoung woman\\b",
    "(?i)\\beyes scanning\\b",
    "(?i)\\bknew would\\b",
    "(?i)\\bfeel sense\\b",
    "(?i)\\blong shadows\\b",
    "(?i)\\bsense unease\\b",
    "(?i)\\bwould never\\b",
    "(?i)\\bthick scent\\b",
    "(?i)\\bsense purpose\\b",
    "(?i)\\brun spine\\b",
    "(?i)\\bshadows across\\b",
    "(?i)\\blooked around\\b",
    "(?i)\\breplied voice\\b",
    "(?i)\\bone day\\b",
    "(?i)\\bvoice laced\\b",
    "(?i)\\bleaned forward\\b",
    "(?i)\\bfell silent\\b",
    "(?i)\\bvoice filled\\b",
    "(?i)\\bknew could\\b",
    "(?i)\\bacross face\\b",
    "(?i)\\bvoice echoing\\b",
    "(?i)\\bstark contrast\\b",
    "(?i)\\bmake sense\\b",
    "(?i)\\blay ahead\\b",
    "(?i)\\bhelp wonder\\b",
    "(?i)\\byoung man\\b",
    "(?i)\\blooked eyes\\b",
    "(?i)\\btook step\\b",
    "(?i)\\bhung air\\b",
    "(?i)\\braised hand\\b",
    "(?i)\\bopened eyes\\b",
    "(?i)\\bsun dipped\\b",
    "(?i)\\bleaned back\\b",
    "(?i)\\bone thing\\b",
    "(?i)\\blet go\\b",
    "(?i)\\bgaze fixed\\b",
    "(?i)\\braised eyebrow\\b",
    "(?i)\\bliving room\\b",
    "(?i)\\beyes narrowing\\b",
    "(?i)\\bold man\\b",
    "(?i)\\bdim light\\b",
    "(?i)\\btilted head\\b",
    "(?i)\\bstumbled upon\\b",
    "(?i)\\bswallowed hard\\b",
    "(?i)\\bflicker something\\b",
    "(?i)\\bready face\\b",
    "(?i)\\bdeep within\\b",
    "(?i)\\blooked like\\b",
    "(?i)\\bsomething far\\b",
    "(?i)\\bcould hear\\b",
    "(?i)\\bnever seen\\b",
    "(?i)\\bgrowing sense\\b",
    "(?i)\\bsmile playing\\b",
    "(?i)\\bstrange sense\\b",
    "(?i)\\bbegan voice\\b",
    "(?i)\\blet us\\b",
    "(?i)\\bever seen\\b",
    "(?i)\\balmost imperceptible\\b",
    "(?i)\\bconstant reminder\\b",
    "(?i)\\bdipped horizon\\b",
    "(?i)\\bunlike anything\\b",
    "(?i)\\balso knew\\b",
    "(?i)\\bplaying lips\\b",
    "(?i)\\bmaybe maybe\\b",
    "(?i)\\bsound like\\b",
    "(?i)\\bfelt chill\\b",
    "(?i)\\blong time\\b",
    "(?i)\\bvoice soft\\b",
    "(?i)\\bfilled air\\b",
    "(?i)\\bhorizon casting\\b",
    "(?i)\\byears ago\\b",
    "(?i)\\bvoice tinged\\b",
    "(?i)\\bfluorescent lights\\b",
    "(?i)\\bback chair\\b",
    "(?i)\\bglimmer hope\\b",
    "(?i)\\bfelt weight\\b",
    "(?i)\\bbeneath feet\\b",
    "(?i)\\bvoice firm\\b",
    "(?i)\\bone one\\b",
    "(?i)\\bleaving behind\\b",
    "(?i)\\bdays turned\\b",
    "(?i)\\bheart pounded\\b",
    "(?i)\\baround room\\b",
    "(?i)\\bwould find\\b",
    "(?i)\\bmixture fear\\b",
    "(?i)\\bcaught eye\\b",
    "(?i)\\bdark lord\\b",
    "(?i)\\bvoice dripping\\b",
    "(?i)\\bstepped closer\\b",
    "(?i)\\bair crackled\\b",
    "(?i)\\bfabric reality\\b",
    "(?i)\\bcaught throat\\b",
    "(?i)\\bheld breath\\b",
    "(?i)\\bface whatever\\b",
    "(?i)\\bface etched\\b",
    "(?i)\\bfigure emerged\\b",
    "(?i)\\bnodded eyes\\b",
    "(?i)\\btrembling slightly\\b",
    "(?i)\\bair around\\b",
    "(?i)\\bchill run\\b",
    "(?i)\\bspreading across\\b",
    "(?i)\\bturned weeks\\b",
    "(?i)\\bsense dread\\b",
    "(?i)\\bnew world\\b",
    "(?i)\\beyes darting\\b",
    "(?i)\\bsense peace\\b",
    "(?i)\\bmind reeling\\b",
    "(?i)\\beyes gleaming\\b",
    "(?i)\\bleft behind\\b",
    "(?i)\\bsomething akin\\b",
    "(?i)\\btrying make\\b",
    "(?i)\\bone would\\b",
    "(?i)\\bopened mouth\\b",
    "(?i)\\bsaid eyes\\b",
    "(?i)\\bvoice echoed\\b",
    "(?i)\\bface pale\\b",
    "(?i)\\bvoice like\\b",
    "(?i)\\bway back\\b",
    "(?i)\\bcould quite\\b",
    "(?i)\\banything ever\\b",
    "(?i)\\blike eternity\\b",
    "(?i)\\bone could\\b",
    "(?i)\\blong since\\b",
    "(?i)\\beyes locked\\b",
    "(?i)\\bbreath caught\\b",
    "(?i)\\bbeneath surface\\b",
    "(?i)\\bwalked away\\b",
    "(?i)\\bechoed mind\\b",
    "(?i)\\bbeacon hope\\b",
    "(?i)\\bcasting warm\\b",
    "(?i)\\blet get\\b",
    "(?i)\\bstep forward\\b",
    "(?i)\\bchapter seven\\b",
    "(?i)\\bmake sure\\b",
    "(?i)\\bcarefully constructed\\b",
    "(?i)\\bturned face\\b",
    "(?i)\\bspoke voice\\b",
    "(?i)\\bfaces etched\\b",
    "(?i)\\beyes widening\\b",
    "(?i)\\bforward eyes\\b",
    "(?i)\\btrying keep\\b",
    "(?i)\\bcleared throat\\b",
    "(?i)\\bcould find\\b",
    "(?i)\\bturned back\\b",
    "(?i)\\blet see\\b",
    "(?i)\\bfelt shiver\\b",
    "(?i)\\bcalled voice\\b",
    "(?i)\\bworld outside\\b",
    "(?i)\\bnext morning\\b",
    "(?i)\\belara felt\\b",
    "(?i)\\bfelt different\\b",
    "(?i)\\bhesitated moment\\b",
    "(?i)\\bfelt familiar\\b",
    "(?i)\\bshiver run\\b",
    "(?i)\\bman named\\b",
    "(?i)\\bacross room\\b",
    "(?i)\\bvoice barely whisper\\b",
    "(?i)\\btook deep breath\\b",
    "(?i)\\bcould help feel\\b",
    "(?i)\\bheart pounding chest\\b",
    "(?i)\\bsaid voice barely\\b",
    "(?i)\\bhelp feel sense\\b",
    "(?i)\\bsaid voice low\\b",
    "(?i)\\bvoice barely audible\\b",
    "(?i)\\basked voice barely\\b",
    "(?i)\\bcould shake feeling\\b",
    "(?i)\\bcasting long shadows\\b",
    "(?i)\\bcould help wonder\\b",
    "(?i)\\bsaid voice steady\\b",
    "(?i)\\bair thick scent\\b",
    "(?i)\\blong shadows across\\b",
    "(?i)\\bsun dipped horizon\\b",
    "(?i)\\bsmile playing lips\\b",
    "(?i)\\bdays turned weeks\\b",
    "(?i)\\bchill run spine\\b",
    "(?i)\\bfelt chill run\\b",
    "(?i)\\bwhispered voice barely\\b",
    "(?i)\\bfelt like eternity\\b",
    "(?i)\\bshiver run spine\\b",
    "(?i)\\bsaid voice filled\\b",
    "(?i)\\bspreading across face\\b",
    "(?i)\\bleaned back chair\\b",
    "(?i)\\bvoice steady despite\\b",
    "(?i)\\bunlike anything ever\\b",
    "(?i)\\bfelt shiver run\\b",
    "(?i)\\btaking deep breath\\b",
    "(?i)\\bbreath caught throat\\b",
    "(?i)\\bready face whatever\\b",
    "(?i)\\bheart pounded chest\\b",
    "(?i)\\broom fell silent\\b",
    "(?i)\\btrying make sense\\b",
    "(?i)\\bdipped horizon casting\\b",
    "(?i)\\bsaid voice trembling\\b",
    "(?i)\\bsomething else something\\b",
    "(?i)\\bdeep breath trying\\b",
    "(?i)\\basked voice trembling\\b",
    "(?i)\\bcould feel weight\\b",
    "(?i)\\bsaid voice firm\\b",
    "(?i)\\bfelt strange sense\\b",
    "(?i)\\bwords hung air\\b",
    "(?i)\\bbrow furrowed concentration\\b",
    "(?i)\\bchallenges lay ahead\\b",
    "(?i)\\bsomething else entirely\\b",
    "(?i)\\bvoice low rumble\\b",
    "(?i)\\bsun began set\\b",
    "(?i)\\bsent shiver spine\\b",
    "(?i)\\bend end end\\b",
    "(?i)\\bvoice trembling slightly\\b",
    "(?i)\\beyes never leaving\\b",
    "(?i)\\bgrowing sense unease\\b",
    "(?i)\\bdoor creaked open\\b",
    "(?i)\\bshake feeling something\\b",
    "(?i)\\bair hung thick\\b",
    "(?i)\\bheart skipped beat\\b",
    "(?i)\\bmade way back\\b",
    "(?i)\\btook step back\\b",
    "(?i)\\brain continued fall\\b",
    "(?i)\\bsun hung low\\b",
    "(?i)\\bsaid voice dripping\\b",
    "(?i)\\bsaid voice soft\\b",
    "(?i)\\bcasting warm glow\\b",
    "(?i)\\btook step forward\\b",
    "(?i)\\beyes wide fear\\b",
    "(?i)\\brenewed sense purpose\\b",
    "(?i)\\bwould find way\\b",
    "(?i)\\btrying keep voice\\b",
    "(?i)\\bhung low sky\\b",
    "(?i)\\bhorizon casting long\\b",
    "(?i)\\bsmile spreading across\\b",
    "(?i)\\bleaned forward eyes\\b",
    "(?i)\\banything ever seen\\b",
    "(?i)\\bone thing certain\\b",
    "(?i)\\bmind racing possibilities\\b",
    "(?i)\\blow sky casting\\b",
    "(?i)\\bsaid voice laced\\b",
    "(?i)\\bheart hammered ribs\\b",
    "(?i)\\bhung heavy air\\b",
    "(?i)\\blooked eyes filled\\b",
    "(?i)\\bface whatever challenges\\b",
    "(?i)\\btook step closer\\b",
    "(?i)\\beyes filled mixture\\b",
    "(?i)\\broad ahead would\\b",
    "(?i)\\bspread like wildfire\\b",
    "(?i)\\bwhispered voice trembling\\b",
    "(?i)\\bfelt sense peace\\b",
    "(?i)\\bhung air heavy\\b",
    "(?i)\\bair thick tension\\b",
    "(?i)\\bnewfound sense purpose\\b",
    "(?i)\\bflicker something akin\\b",
    "(?i)\\bgrin spreading across\\b",
    "(?i)\\bdeep breath stepped\\b",
    "(?i)\\bdoor swung open\\b",
    "(?i)\\bknew would never\\b",
    "(?i)\\beyes locked onto\\b",
    "(?i)\\btried make sense\\b",
    "(?i)\\bdust motes danced\\b",
    "(?i)\\bdimly lit room\\b",
    "(?i)\\bsmall intricately carved\\b",
    "(?i)\\bbrow furrowed confusion\\b",
    "(?i)\\bdeep breath steeling\\b",
    "(?i)\\bcould help notice\\b",
    "(?i)\\bone last time\\b",
    "(?i)\\beyes darting around\\b",
    "(?i)\\bsent shivers spine\\b",
    "(?i)\\bkeep voice steady\\b",
    "(?i)\\byoung woman named\\b",
    "(?i)\\bsaid voice tinged\\b",
    "(?i)\\bpainting sky hues\\b",
    "(?i)\\beyes wide wonder\\b",
    "(?i)\\bnodded mind racing\\b",
    "(?i)\\bfingers flying across\\b",
    "(?i)\\bwhatever challenges lay\\b",
    "(?i)\\bfigure emerged shadows\\b",
    "(?i)\\bmind raced trying\\b",
    "(?i)\\bknew road ahead\\b",
    "(?i)\\braised hand silencing\\b",
    "(?i)\\bpiercing blue eyes\\b",
    "(?i)\\bfelt strange sensation\\b",
    "(?i)\\bturned walked away\\b",
    "(?i)\\bsaid voice calm\\b",
    "(?i)\\bsmall smile playing\\b",
    "(?i)\\bfelt cold dread\\b",
    "(?i)\\bmind racing questions\\b",
    "(?i)\\bcould find way\\b",
    "(?i)\\bspread across face\\b",
    "(?i)\\bfirst time long\\b",
    "(?i)\\bground beneath feet\\b",
    "(?i)\\bhung thick scent\\b",
    "(?i)\\bsky casting long\\b",
    "(?i)\\bmind racing implications\\b",
    "(?i)\\bweeks weeks months\\b",
    "(?i)\\basked voice low\\b",
    "(?i)\\bchill ran spine\\b",
    "(?i)\\bsaid trying sound\\b",
    "(?i)\\bwould never forget\\b",
    "(?i)\\bgaze sweeping across\\b",
    "(?i)\\basked voice laced\\b",
    "(?i)\\bshiver ran spine\\b",
    "(?i)\\bturned weeks weeks\\b",
    "(?i)\\bspent countless hours\\b",
    "(?i)\\bbrow furrowed concern\\b",
    "(?i)\\beyes wide mixture\\b",
    "(?i)\\bresonated deep within\\b",
    "(?i)\\beyes widened surprise\\b",
    "(?i)\\bair thick anticipation\\b",
    "(?i)\\bbreath catching throat\\b",
    "(?i)\\bmind racing tried\\b",
    "(?i)\\bdeep breath feeling\\b",
    "(?i)\\blooked around room\\b",
    "(?i)\\bshook head trying\\b",
    "(?i)\\bwhatever lay ahead\\b",
    "(?i)\\bsaid voice like\\b",
    "(?i)\\breplied voice steady\\b",
    "(?i)\\beyes scanning room\\b",
    "(?i)\\bfelt growing sense\\b",
    "(?i)\\bstepped forward voice\\b",
    "(?i)\\bnever seen anything\\b",
    "(?i)\\bstammered voice barely\\b",
    "(?i)\\bhelp feel twinge\\b",
    "(?i)\\bknew one thing\\b",
    "(?i)\\bstepped forward eyes\\b",
    "(?i)\\bsmile spread across\\b",
    "(?i)\\bmaybe maybe could\\b",
    "(?i)\\bfeel sense unease\\b",
    "(?i)\\bseen anything like\\b",
    "(?i)\\bknew chilling certainty\\b",
    "(?i)\\bgrowing sense dread\\b",
    "(?i)\\bintricately carved wooden\\b",
    "(?i)\\bheart heavy weight\\b",
    "(?i)\\bwords echoed mind\\b",
    "(?i)\\bsighed running hand\\b",
    "(?i)\\bscent damp earth\\b",
    "(?i)\\bair thick smell\\b",
    "(?i)\\bsaid voice smooth\\b",
    "(?i)\\bbegan set casting\\b",
    "(?i)\\bblood ran cold\\b",
    "(?i)\\bsaid voice echoing\\b",
    "(?i)\\bhand instinctively reaching\\b",
    "(?i)\\bsense peace wash\\b",
    "(?i)\\belara said voice\\b",
    "(?i)\\bsmile tugging corners\\b",
    "(?i)\\bsaid voice tight\\b",
    "(?i)\\bcould feel power\\b",
    "(?i)\\beyes wide terror\\b",
    "(?i)\\bmind already racing\\b",
    "(?i)\\bknuckles turning white\\b",
    "(?i)\\bfelt glimmer hope\\b",
    "(?i)\\bmade decision would\\b",
    "(?i)\\bfaint almost imperceptible\\b",
    "(?i)\\beyes widened shock\\b",
    "(?i)\\bfeel sense pride\\b",
    "(?i)\\btears streaming face\\b",
    "(?i)\\bhorizon painting sky\\b",
    "(?i)\\bcasting eerie glow\\b",
    "(?i)\\blong could remember\\b",
    "(?i)\\bcontinued fall washing\\b",
]
COMPILED_REGEX_PATTERNS = [re.compile(pattern) for pattern in REGEX_PATTERNS]
