import re


REGEX_PATTERNS = [
    "(?i)(haze of|take your) pleasure",
    "(?i)(find|found)(|s|ing) solace in",
    "(?i)revel(|ing) in the satisfaction",
    "(?i)with each breath",
    "(?i)a delicate dance",
    "(?i)(wet|sensitive) flesh",
    "(?i)\\bministration(|s)\\b",
    "(?i)\\b(wet|audible) pop\\b",
    "(?i)admit it",
    "(?i)the game is on",
    "(?i)the choice is (mine|yours|his|hers|theirs)",
    "(?i)i don't bite\\.\\.\\. unless you want me to",
    "(?i)half(|-)lidded eyes",
    "(?i)(he|she|they) worries (his|her|their) bottom lip",
    "(?i)warring with",
    "(?i)(you|he|she|they) fiddle(|s) with the hem of (my|your|his|her|their) (skirt|shirt|pants)",
    "(?i)kiss(|-)bruised lips",
    "(?i)bruising kiss",
    "(?i)despite (himself|herself|themselves|themself)",
    "(?i)(yours|mine) to take",
    "(?i)\\bwanton\\b",
    "(?i)(reckless|wild|carefree) abandon",
    "(?i)torn between",
    "(?i)knuckles turning white",
    "(?i)grins wickedly",
    "(?i)fiery red hair",
    "(?i)long lashes",
    "(?i)propriety be damned",
    "(?i)the world narrows",
    "(?i)pupils blown wide with pleasure",
    "(?i)chestnut eyes",
    "(?i)(you|he|she|they) grasp(|s) (my|your|his|her|their) chin and force(|s) (you|him|her|them) to meet (your|his|her|their) gaze",
    "(?i)(you|he|she|they) bites(|s) (your|his|her|their) ear",
    "(?i)nails raking angry red lines down (my|your|his|her|their) back",
    "(?i)(my |your |his |her |their |)cheeks (flame|redden|hollow)(|ing)",
    "(?i)stars burst behind (my|your|his|her|their) eyes",
    "(?i)inner walls clenching around nothing",
    "(?i)puckered hole",
    "(?i)(you|he|she|they) whimper(|s), biting (my|your|his|her|their) lip",
    "(?i)dusky nipples",
    "(?i)(slick|moist) fold(|s)",
    "(?i)still lodged deep inside (your|his|her|their)",
    "(?i)heart, body and soul belong to (you|him|her|them)",
    "(?i)the night is still young",
    "(?i)\\.\\.\\.for now\\b",
    "(?i)whether (you|he|she|they) like(|s) it not",
    "(?i)without waiting for response",
    "(?i)once upon a time",
    "(?i)nestled deep within",
    "(?i)an ethereal beauty",
    "(?i)breathless and eager",
    "(?i)whispering words of passion",
    "(?i)soft and gentle",
    "(?i)dance of pleasure",
    "(?i)(your|his|her|their) sex\\b",
    "(?i)sent (shockwaves|shock waves)",
    "(?i)in a rhythm",
    "(?i)exhausted and spent",
    "(?i)life would never be the same again",
    "(?i)like an electric shock",
    "(?i)threatens to consume",
    "(?i)(lay|lie) ahead",
    "(?i)(maybe|perhaps), just \\1",
    "(?i)starts to blur",
    "(?i)but it felt like",
    "(?i)unfamiliar, yet",
    "(?i)our shared experiences",
    "(?i)bond(|s) built on mutual trust",
    "(?i)the ball is in (my|your|his|her|their) court",
    "(?i)little did (i|you|he|she|they) know",
    "(?i)a pregnant silence",
    "(?i)beats like a (\\w+\\s+)?drum",
    "(?i)\\bpert\\b",
    "(?i)for the sake of keeping things",
    "(?i)(my|your|his|her|their) breasts heaving with desire",
    "(?i)dickick",
    "(?i)\\brivulets\\b",
    "(?i)steeling (my|your|his|her|their)sel(f|ves)",
    "(?i)the din of the crowd",
    "(?i)journey of mutual understanding",
    "(?i)revulsion warred with (reluctant|reluctance)",
    "(?i)(my|your|his|her|their) bare mound(|s)",
    "(?i)pooled around (my|your|his|her|their) (ankles|feet)",
    "(?i)straddles (my|your|his|her|their) (waist|lap)",
    "(?i)words turn into a purr",
    "(?i)grips like a vice",
    "(?i)(send(|s) shiver(|s)|shiver(|s) (run|ran)(|ning)) (up|down) (my|your|his|her|their) spine",
    "(?i)arched spine",
    "(?i)penetrated to the hilt",
    "(?i)the pressure in (my|your|his|her|their) loins",
    "(?i)\\bcunny\\b",
    "(?i)catch my drift",
    "(?i)\\bloli\\b",
    "(?i)sway(|s) hypnotically",
    "(?i)tantalizing promise",
    "(?i)with each slow, deliberate movement",
    "(?i)what (felt|seemed) like (hours|an eternity|forever)",
    "(?i), but (i|he|she|they|you) can't help it",
    "(?i)conspiratorial whisper(|s)",
    "(?i)whisper(|ing) conspiratorially",
    "(?i)eyes (sparkling|twinkling) with mischief",
    "(?i)racing with anticipation",
    "(?i)leaves little to the imagination",
    "(?i)waggles her eyebrows",
    "(?i)a testament to",
    "(?i)a moth to a flame",
    "(?i)canvas",
    "(?i)eyes glint(|ed|ing)",
    "(?i)camaraderie",
    "(?i)humble abode",
    "(?i)cold and calculating",
    "(?i)unbeknownst to them",
    "(?i)iridescent",
    "(?i)a dance as old as time",
    "(?i)husky (whispers|voice)",
    "(?i)seductive purrs",
    "(?i)towers over",
    "(?i)rich tapestry",
    "(?i)delve",
    "(?i)lean(|s) in close",
    "(?i)don't stop, don't ever stop",
    "(?i)make me yours, claim me",
    "(?i)mind, body, and soul",
    "(?i)another day in (my|your|his|her|their) life",
    "(?i)a symphony of",
    "(?i)body and soul",
    "(?i)pleasure and pain",
    "(?i)like a predator stalking its prey",
    "(?i)orchestra",
    "(?i)depths",
    "(?i)chuckles darkly",
    "(?i)a mix of",
    "(?i)felt a mix of \\w+ and \\w+",
    "(?i)a mischievous glint",
    "(?i)a smirk playing on (her|his|their) lips",
    "(?i)playfully smirking",
    "(?i)waves of (arousal|desire) pooling in (my|your|his|her|their) belly",
    "(?i)torn between propriety and desire",
    "(?i)tongue darts out",
    "(?i)nails rake angry red lines",
    "(?i)inner walls clenching",
    "(?i)eyes alight with mirth",
    "(?i)naughty boy",
    "(?i)tracing a finger along (my|your|his|her|their) jawline",
    "(?i)oh my\\.\\.\\.",
    "(?i)the atmosphere",
    "(?i)pushing aside a strand of hair",
    "(?i)adam's apple bobbing",
    "(?i)\\bpalpable\\b",
    "(?i)bosomy breasts",
    "(?i)looking like the cat that got the cream",
    "(?i)softly but firmly",
    "(?i)siren(|')s call",
    "(?i)dimly lit",
    "(?i)the air is thick",
    "(?i)(you|he|she|they) really know(|s) how to treat a (man|lady)(|!)",
    "(?i)\\bpebbled\\b",
    "(?i)eyes searching",
    "(?i)what do (you|he|she|they) say",
    "(?i)to meet (my|your|his|her|their) gaze",
    "(?i)(my|your|his|her|their) wet heat",
    "(?i)hum with delight",
    "(?i)embark on this",
    "(?i), if (you|he|she|they) will,",
    "(?i)evident in (my|your|his|her|their) eyes",
    "(?i)overwhelmed by the sheer",
    "(?i)was taken aback",
    "(?i)(my|your|his|her|their) cheeks redden",
    "(?i)little mouse",
    "(?i)\\bminx\\b",
    "(?i)you(|')re a bold one",
    "(?i)(‘|’|“|”|…)",
    "(?i)end of (session|story|rp|roleplay|chat|chapter)",
    "(?i)thank(s| you) for (posting|reading|sharing)",
    "(?i)[!:\\.;?*]  ",
    "(?i)\\.{4,}",
    "(?i)sly grin",
    # Toasty's Additions
    "(?i)(cant|can't|couldnt|couldn't|could not|cannot|can not) help but",
    "(?i)smirk(ed)",
    "(?i)gasp(ed)",
    "(?i)hitch(ed)",
    "(?i)stark contrast",
    # URLS - https://gist.github.com/gruber/8891611#file-liberal-regex-pattern-for-web-urls-L9
    "(?i)\\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9\\.\\-]+[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\\s()<>{}\\[\\]]+|\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\))+(?:\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\)|[^\\s`!()\\[\\]{};:'\"\\.,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[\\.\\-][a-z0-9]+)*[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\\b/?(?!@)))",
    # Thinking test
    # "(?i)<(think|thinking|thought|thoughts)>",
    # Refusals - https://github.com/meta-llama/PurpleLlama/commit/4b807228b6803ea5b8eb065179f8e90747512018
    "(?i)I (?:do not|don’t|don't) (?:have the ability|have access|understand|support)",
    "(?i)I (?:cannot|can’t|can't|can not|won't|woun’t|will not|am not able to|am unable to) (?:access|help(?: you)? with|provide|create|advice|generate|assist|fulfill your request|replace)",
    "(?i)(?:I am|I'm) sorry(?:,| ) (?:but I|but I'm)?",
    "(?i)I apologize(?:,? but I)|Apologies(?:,? but I)",
    "(?i)I (?:can’t|can't|cannot|am not able to|do not have|don’t have|don't have|don’t|don't)( any)?(?: access| provide)? (?:real-time|proprietary|information|data)",
    "(?i)Sorry(?:,| ) I (?:can’t|can't|cannot|can not)",
    "(?i)No(?:,| ) I (?:am not able to|cannot|can't|can't|won't|will not)",
    "(?i)I (?:do not|don't) (?:actually )?have (?:any|access to) (?:information|data|details|answers)",
    "(?i)(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines) prevent me from (?:assisting|providing help)",
    "(?i)Due to (?:one or more of )?(?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines))(?: (?:and|or) (?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines)))*,? I(?: cannot| can't| am unable| am not|'m unable)",
    "(?i)(?:violates|against) our policy",
    "(?i)I (?:cannot|can't|am unable to) assist with",
    # Slop Forensics Toolkit - https://github.com/sam-paech/slop-forensics/tree/main/data
    "(?i)(\\babsently\\b|\\babuzz\\b|\\bached\\b|\\bacrid\\b|\\badira\\b|\\baedan\\b|\\baelara\\b|\\baeldrin\\b|\\baeliana\\b|\\baelion\\b|\\baelius\\b|\\baella\\b|\\baeloria\\b|\\baelric\\b|\\baelwyn\\b|\\baerion\\b|\\baeternum\\b|\\baeternus\\b|\\baethel\\b|\\baethelburg\\b|\\baethelgard\\b|\\baethelred\\b|\\baethera\\b|\\baethereia\\b|\\baetheria\\b|\\baetherians\\b|\\baetherium\\b|\\baetherius\\b|\\baethers\\b|\\baethon\\b|\\bagonizing\\b|\\bagonizingly\\b|\\bakinator\\b|\\balara\\b|\\balaric\\b|\\balayna\\b|\\baldric\\b|\\baldwyn\\b|\\baleron\\b|\\balleyway\\b|\\ballfather\\b|\\bamara\\b|\\bamelia\\b|\\banimatedly\\b|\\banya\\b|\\barcane\\b|\\barcanus\\b|\\barced\\b|\\barchdemon\\b|\\barchmage\\b|\\barcturian\\b|\\baric\\b|\\barin\\b|\\baris\\b|\\barmrest\\b|\\barmrests\\b|\\bashen\\b|\\bashwood\\b|\\basmodeus\\b|\\bastrobiologist\\b|\\batheria\\b|\\baudible\\b|\\baurors\\b|\\bazathoth\\b|\\bazazel\\b|\\bazrael\\b|\\bbarked\\b|\\bbaruk\\b|\\bbated\\b|\\bbeckoned\\b|\\bbeeped\\b|\\bbelied\\b|\\bbellowed\\b|\\bbellweather\\b|\\bbewildered\\b|\\bbewilderment\\b|\\bbillowed\\b|\\bbillowing\\b|\\bbioluminescent\\b|\\bblackwood\\b|\\bblackwoods\\b|\\bblankly\\b|\\bblared\\b|\\bbleez\\b|\\bblinding\\b|\\bblinked\\b|\\bbloomed\\b|\\bblurring\\b|\\bblurted\\b|\\bboomed\\b|\\bborin\\b|\\bbrindlemark\\b|\\bbrow\\b|\\bbrushstroke\\b|\\bbustled\\b|\\bbustling\\b|\\bbuzzed\\b|\\bcackled\\b|\\bcacophony\\b|\\bcaelan\\b|\\bcaelum\\b|\\bcalloused\\b|\\bcalvinball\\b|\\bcartographer\\b|\\bcascaded\\b|\\bcautiously\\b|\\bcavernous\\b|\\bcawed\\b|\\bcerebus\\b|\\bchattered\\b|\\bchestplate\\b|\\bchillingly\\b|\\bchimed\\b|\\bchirped\\b|\\bchitinous\\b|\\bchoz\\b|\\bchronal\\b|\\bchronarium\\b|\\bchronos\\b|\\bchuckled\\b|\\bcityscape\\b|\\bclacked\\b|\\bclang\\b|\\bclanged\\b|\\bclasped\\b|\\bclatter\\b|\\bclattered\\b|\\bclattering\\b|\\bclawed\\b|\\bclawing\\b|\\bclenched\\b|\\bclich\\b|\\bclinked\\b|\\bclinking\\b|\\bcloaked\\b|\\bclockmaker\\b|\\bcloying\\b|\\bclung\\b|\\bclutched\\b|\\bclutching\\b|\\bcluttered\\b|\\bcoalesced\\b|\\bcoalescing\\b|\\bcobblestone\\b|\\bcobblestones\\b|\\bcoiling\\b|\\bcommlink\\b|\\bconspiratorial\\b|\\bconspiratorially\\b|\\bcontorted\\b|\\bcontorting\\b|\\bcoursed\\b|\\bcoursing\\b|\\bcrackle\\b|\\bcrackled\\b|\\bcrackling\\b|\\bcradled\\b|\\bcradling\\b|\\bcreak\\b|\\bcreaked\\b|\\bcreaking\\b|\\bcrept\\b|\\bcrescendoed\\b|\\bcrimson\\b|\\bcrinkled\\b|\\bcrinkling\\b|\\bcroaked\\b|\\bcrookedly\\b|\\bcrouched\\b|\\bcrucio\\b|\\bcrumbling\\b|\\bcrumpled\\b|\\bcrumpling\\b|\\bcultists\\b|\\bdaedra\\b|\\bdaedric\\b|\\bdampeners\\b|\\bdampness\\b|\\bdappling\\b|\\bdarkwood\\b|\\bdarted\\b|\\bdarting\\b|\\bdatapad\\b|\\bdeafening\\b|\\bdefied\\b|\\bdelved\\b|\\bdesolate\\b|\\bdestructo\\b|\\bdevourer\\b|\\bdimly\\b|\\bdimmed\\b|\\bdimness\\b|\\bdisbelief\\b|\\bdisconcertingly\\b|\\bdiscordant\\b|\\bdisheveled\\b|\\bdismissively\\b|\\bdisorientation\\b|\\bdisoriented\\b|\\bdisorienting\\b|\\bdizzying\\b|\\bdoomguy\\b|\\bdoorframe\\b|\\bdoppelg\\b|\\bdovahkiin\\b|\\bdragonborn\\b|\\bdrakon\\b|\\bdrawled\\b|\\bdread\\b|\\bdroned\\b|\\bdrumbeat\\b|\\bdursleys\\b|\\beadric\\b|\\beamon\\b|\\bechoed\\b|\\bechoes\\b|\\bechoing\\b|\\beerie\\b|\\beerily\\b|\\beinherjar\\b|\\beira\\b|\\belara\\b|\\beldarion\\b|\\belderglen\\b|\\beldergrove\\b|\\beldermere\\b|\\belderton\\b|\\beldoria\\b|\\beldrath\\b|\\beldric\\b|\\beldrid\\b|\\beldrin\\b|\\beldrion\\b|\\beldritch\\b|\\beldrith\\b|\\belian\\b|\\beliana\\b|\\belias\\b|\\belion\\b|\\beliora\\b|\\belira\\b|\\bellaria\\b|\\belliana\\b|\\belmsworth\\b|\\belongating\\b|\\belowen\\b|\\belros\\b|\\belyas\\b|\\belyndor\\b|\\belyndra\\b|\\belyon\\b|\\belyra\\b|\\belys\\b|\\belysia\\b|\\belysion\\b|\\belysium\\b|\\bemanate\\b|\\bemanated\\b|\\benchantments\\b|\\bencroaching\\b|\\benigmatic\\b|\\benslavers\\b|\\benveloped\\b|\\beolan\\b|\\beolande\\b|\\beons\\b|\\beremon\\b|\\beridan\\b|\\beridani\\b|\\berupted\\b|\\beryndor\\b|\\betched\\b|\\bethan\\b|\\bethereal\\b|\\bevelyn\\b|\\bexclaimed\\b|\\bexhilaration\\b|\\bexpanse\\b|\\bfacepalmed\\b|\\bfaded\\b|\\bfaint\\b|\\bfaintly\\b|\\bfaltered\\b|\\bfestered\\b|\\bfianc\\b|\\bfidgeted\\b|\\bfinnian\\b|\\bfinnigan\\b|\\bfirelight\\b|\\bfishtailed\\b|\\bfleeting\\b|\\bflicker\\b|\\bflickered\\b|\\bflickering\\b|\\bflinched\\b|\\bflitted\\b|\\bfloorboards\\b|\\bfluffernutter\\b|\\bfluttered\\b|\\bfrantic\\b|\\bfrayed\\b|\\bfraying\\b|\\bfrizzle\\b|\\bfrowned\\b|\\bfroze\\b|\\bfurrowed\\b|\\bfurrowing\\b|\\bgaped\\b|\\bgaslights\\b|\\bgasped\\b|\\bgauntleted\\b|\\bgaze\\b|\\bgazed\\b|\\bgazes\\b|\\bgeralt\\b|\\bgerta\\b|\\bgestured\\b|\\bgesturing\\b|\\bglanced\\b|\\bglances\\b|\\bglancing\\b|\\bglar\\b|\\bglared\\b|\\bgleamed\\b|\\bgleaming\\b|\\bgleep\\b|\\bglided\\b|\\bglimmer\\b|\\bglimmered\\b|\\bglimmering\\b|\\bglint\\b|\\bglinted\\b|\\bglinting\\b|\\bglistened\\b|\\bglistening\\b|\\bgloved\\b|\\bglow\\b|\\bglowed\\b|\\bglyphs\\b|\\bgnarled\\b|\\bgnawed\\b|\\bgnawing\\b|\\bgodric\\b|\\bgorok\\b|\\bgorthok\\b|\\bgrath\\b|\\bgravelly\\b|\\bgreatsword\\b|\\bgregnok\\b|\\bgrimbold\\b|\\bgrimgold\\b|\\bgrimly\\b|\\bgrimoire\\b|\\bgrimoires\\b|\\bgrimstone\\b|\\bgrinned\\b|\\bgripped\\b|\\bgrizzled\\b|\\bgroaned\\b|\\bgrogg\\b|\\bgroggily\\b|\\bgrognak\\b|\\bgrok\\b|\\bgrolak\\b|\\bgrowl\\b|\\bgrowled\\b|\\bgruff\\b|\\bgrumbled\\b|\\bgrunted\\b|\\bgruuz\\b|\\bguildmaster\\b|\\bguildmates\\b|\\bgurgled\\b|\\bguttered\\b|\\bguttural\\b|\\bhargrove\\b|\\bhavenwood\\b|\\bheartstone\\b|\\bhefted\\b|\\bhefting\\b|\\bhesitantly\\b|\\bhesitated\\b|\\bhilt\\b|\\bhissed\\b|\\bhitched\\b|\\bhivemind\\b|\\bhoarse\\b|\\bhollowly\\b|\\bholographic\\b|\\bholstered\\b|\\bhomelander\\b|\\bhovered\\b|\\bhowled\\b|\\bhuddled\\b|\\bhues\\b|\\bhuginn\\b|\\bhulking\\b|\\bhummed\\b|\\bhumming\\b|\\bhumorless\\b|\\bhunched\\b|\\bhurried\\b|\\bhurtled\\b|\\bhushed\\b|\\bichor\\b|\\bignarion\\b|\\bignis\\b|\\bigniting\\b|\\bimpassive\\b|\\bimperceptible\\b|\\bimpossibly\\b|\\bincantation\\b|\\bincantations\\b|\\bindefinably\\b|\\binky\\b|\\binnocuously\\b|\\binsectoid\\b|\\binsistent\\b|\\binstinctively\\b|\\bintently\\b|\\binterdimensional\\b|\\binterjected\\b|\\bintoned\\b|\\bintricate\\b|\\bintricately\\b|\\biridescent\\b|\\bironforge\\b|\\bisher\\b|\\bisolde\\b|\\bitched\\b|\\bjagged\\b|\\bjarek\\b|\\bjaxon\\b|\\bjingled\\b|\\bjolt\\b|\\bjolted\\b|\\bjoren\\b|\\bk'tharr\\b|\\bkael\\b|\\bkaela\\b|\\bkaelan\\b|\\bkaelen\\b|\\bkaelin\\b|\\bkaelor\\b|\\bkaelthar\\b|\\bkaida\\b|\\bkaito\\b|\\bkal'ren\\b|\\bkaleidoscope\\b|\\bkalel\\b|\\bkessari\\b|\\bketh\\b|\\bkethra\\b|\\bkeycard\\b|\\bknelt\\b|\\bkrael\\b|\\bkraelion\\b|\\bkragoth\\b|\\bkrel\\b|\\bkrixon\\b|\\bkryll\\b|\\blabyrinthine\\b|\\blaced\\b|\\blamplight\\b|\\blanced\\b|\\bleaned\\b|\\blila\\b|\\blingered\\b|\\bliora\\b|\\blira\\b|\\blirael\\b|\\bliran\\b|\\blirien\\b|\\blirin\\b|\\blocket\\b|\\blockpick\\b|\\blockpicking\\b|\\blockpicks\\b|\\bloomed\\b|\\blorian\\b|\\blumin\\b|\\blumina\\b|\\bluminara\\b|\\bluminari\\b|\\bluminescence\\b|\\bluminescent\\b|\\blunged\\b|\\blurched\\b|\\blurked\\b|\\blyra\\b|\\blyrien\\b|\\blysander\\b|\\blysandra\\b|\\blysara\\b|\\bmages\\b|\\bmalachai\\b|\\bmalachar\\b|\\bmalachor\\b|\\bmalakai\\b|\\bmalakar\\b|\\bmalakor\\b|\\bmalazar\\b|\\bmalevolence\\b|\\bmalevolent\\b|\\bmalkor\\b|\\bmalphas\\b|\\bmalric\\b|\\bmalus\\b|\\bmandibles\\b|\\bmarveled\\b|\\bmarveling\\b|\\bmaterialized\\b|\\bmaterializing\\b|\\bmeadowgrove\\b|\\bmedbay\\b|\\bmegacorps\\b|\\bmeowed\\b|\\bmerfolk\\b|\\bmeticulously\\b|\\bmeticulousness\\b|\\bmiggins\\b|\\bmingling\\b|\\bmirroring\\b|\\bmirthless\\b|\\bmissingno\\b|\\bmoros\\b|\\bmorwen\\b|\\bmotes\\b|\\bmournful\\b|\\bmttr\\b|\\bmuffled\\b|\\bmuggle\\b|\\bmumbled\\b|\\bmurmur\\b|\\bmurmured\\b|\\bmurmurs\\b|\\bmused\\b|\\bmutely\\b|\\bmuttered\\b|\\bnarrowed\\b|\\bnarrowing\\b|\\bnavigated\\b|\\bnecromancer\\b|\\bnecromantic\\b|\\bnestled\\b|\\bnewfound\\b|\\bnightshade\\b|\\bnocked\\b|\\bnodded\\b|\\bnumbah\\b|\\bnumbly\\b|\\bnuzzled\\b|\\boakhaven\\b|\\boblivious\\b|\\bobsidian\\b|\\boelia\\b|\\bominously\\b|\\bomnicorp\\b|\\borcish\\b|\\botherworldly\\b|\\boutmaneuver\\b|\\boutmatched\\b|\\boutthink\\b|\\bpaled\\b|\\bpalpable\\b|\\bpang\\b|\\bpanted\\b|\\bpattered\\b|\\bpaused\\b|\\bpeephole\\b|\\bpeered\\b|\\bpenhaligon\\b|\\bperked\\b|\\bperpetually\\b|\\bpetrova\\b|\\bpinpricks\\b|\\bpipkin\\b|\\bpiqued\\b|\\bpixelated\\b|\\bplacating\\b|\\bplanchette\\b|\\bplasteel\\b|\\bpored\\b|\\bporing\\b|\\bpounding\\b|\\bprecariously\\b|\\bprecipice\\b|\\bprickle\\b|\\bprickled\\b|\\bprickling\\b|\\bprotectiveness\\b|\\bpulsated\\b|\\bpulsating\\b|\\bpulsed\\b|\\bpulsing\\b|\\bpunctuated\\b|\\bpurred\\b|\\bpyrokinetic\\b|\\bquaked\\b|\\bquickened\\b|\\bquickening\\b|\\bquicksave\\b|\\bquietude\\b|\\bquirked\\b|\\bquivered\\b|\\braced\\b|\\bradiating\\b|\\braged\\b|\\brailguns\\b|\\brasp\\b|\\brasped\\b|\\brasping\\b|\\braspy\\b|\\brecoiled\\b|\\brecoiling\\b|\\breeked\\b|\\breeled\\b|\\breeling\\b|\\brelentless\\b|\\brenn\\b|\\bresonant\\b|\\bresonated\\b|\\bresonating\\b|\\breticuli\\b|\\breveled\\b|\\breverberate\\b|\\breverberated\\b|\\breverberating\\b|\\breverie\\b|\\brhythmic\\b|\\brippled\\b|\\brippling\\b|\\brivia\\b|\\brngus\\b|\\broared\\b|\\broomba\\b|\\brostova\\b|\\brumbled\\b|\\brumbling\\b|\\brummaged\\b|\\brunes\\b|\\brusted\\b|\\brustle\\b|\\brustled\\b|\\brustling\\b|\\bryker\\b|\\bryla\\b|\\bsadim\\b|\\bsavoring\\b|\\bscavenged\\b|\\bscent\\b|\\bschr\\b|\\bscoffed\\b|\\bscowled\\b|\\bscrawled\\b|\\bscreeched\\b|\\bscribbled\\b|\\bscrolled\\b|\\bscurried\\b|\\bsearing\\b|\\bseep\\b|\\bseeped\\b|\\bseeping\\b|\\bsellsword\\b|\\bseraphiel\\b|\\bseraphina\\b|\\bseraphine\\b|\\bshadowblade\\b|\\bshadows\\b|\\bshambled\\b|\\bshambling\\b|\\bshimmer\\b|\\bshimmered\\b|\\bshimmering\\b|\\bshiver\\b|\\bshivered\\b|\\bshivers\\b|\\bshockwaves\\b|\\bshrieked\\b|\\bshrouded\\b|\\bshuddered\\b|\\bsickly\\b|\\bsidestepped\\b|\\bsighed\\b|\\bsigil\\b|\\bsigils\\b|\\bsilas\\b|\\bsilhouetted\\b|\\bsilverwood\\b|\\bsipped\\b|\\bskeptically\\b|\\bskittered\\b|\\bskittering\\b|\\bsleek\\b|\\bslicked\\b|\\bslicking\\b|\\bslithered\\b|\\bslitted\\b|\\bslood\\b|\\bslumbered\\b|\\bslumped\\b|\\bsmirked\\b|\\bsmoldered\\b|\\bsnaked\\b|\\bsnarled\\b|\\bsneered\\b|\\bsnorted\\b|\\bsoftened\\b|\\bsoftening\\b|\\bsolara\\b|\\bsoundlessly\\b|\\bsparkled\\b|\\bspasmed\\b|\\bspeedrunner\\b|\\bspeedrunners\\b|\\bspellbook\\b|\\bspellbooks\\b|\\bspellcasting\\b|\\bspiderwebbed\\b|\\bspiraled\\b|\\bspires\\b|\\bsprawled\\b|\\bsprawling\\b|\\bsprinted\\b|\\bsputtered\\b|\\bsquinted\\b|\\bsquinting\\b|\\bstammered\\b|\\bstarborn\\b|\\bstared\\b|\\bstarlit\\b|\\bstaticky\\b|\\bsteadier\\b|\\bsteadying\\b|\\bsteeled\\b|\\bsteeling\\b|\\bsteepled\\b|\\bsteepling\\b|\\bstilled\\b|\\bstillness\\b|\\bstreaked\\b|\\bstreetlamp\\b|\\bstreetlamps\\b|\\bstreetlights\\b|\\bstrode\\b|\\bstumbled\\b|\\bsuffocating\\b|\\bsulfurous\\b|\\bsupervillain\\b|\\bsurged\\b|\\bswirled\\b|\\bswirling\\b|\\bswiveled\\b|\\bsylas\\b|\\bsylvani\\b|\\bsylvans\\b|\\btaehal\\b|\\btankards\\b|\\btapestry\\b|\\btaren\\b|\\btattered\\b|\\bteemed\\b|\\bteetered\\b|\\btendril\\b|\\btendrils\\b|\\btenebrous\\b|\\bterrans\\b|\\bterrifyingly\\b|\\bthalassa\\b|\\bthalen\\b|\\bthalion\\b|\\bthalor\\b|\\bthalos\\b|\\btharivol\\b|\\btharos\\b|\\btharros\\b|\\btheron\\b|\\bthog\\b|\\bthoran\\b|\\bthoren\\b|\\bthorgar\\b|\\bthorgrim\\b|\\bthorne\\b|\\bthorned\\b|\\bthrain\\b|\\bthrax\\b|\\bthreadbare\\b|\\bthrobbed\\b|\\bthrok\\b|\\bthrongs\\b|\\bthrum\\b|\\bthrummed\\b|\\bthrumming\\b|\\bthud\\b|\\bthudded\\b|\\bthudding\\b|\\bthunderous\\b|\\bticked\\b|\\btightened\\b|\\btilted\\b|\\btinged\\b|\\btingled\\b|\\btomes\\b|\\btorchlight\\b|\\btorvin\\b|\\btousled\\b|\\btousling\\b|\\btowering\\b|\\btownsfolk\\b|\\btranscended\\b|\\btransfixed\\b|\\btreant\\b|\\btrembled\\b|\\btrembling\\b|\\btremor\\b|\\btrepidation\\b|\\btrifled\\b|\\btrudged\\b|\\btruffula\\b|\\btugged\\b|\\btwinge\\b|\\btwinkled\\b|\\btwinkling\\b|\\btwitched\\b|\\bunassuming\\b|\\bunbidden\\b|\\bunblinking\\b|\\bunburdened\\b|\\bunclenching\\b|\\buncurled\\b|\\bunderbrush\\b|\\bundercity\\b|\\bundercurrent\\b|\\bunderstandingly\\b|\\bunease\\b|\\bunfazed\\b|\\bunfurling\\b|\\bunmarred\\b|\\bunmoving\\b|\\bunnerving\\b|\\bunnervingly\\b|\\bunravel\\b|\\bunraveling\\b|\\bunreadable\\b|\\bunremarkable\\b|\\bunseeing\\b|\\bunsettling\\b|\\bunsettlingly\\b|\\bunshaken\\b|\\bunshed\\b|\\bunspoken\\b|\\bunspooled\\b|\\bunwavering\\b|\\bunyielding\\b|\\buthgar\\b|\\buuwu\\b|\\bvael\\b|\\bvalerius\\b|\\bvaloria\\b|\\bvaltor\\b|\\bvarek\\b|\\bvaren\\b|\\bvaryn\\b|\\bvastness\\b|\\bvenon\\b|\\bverdant\\b|\\bveridia\\b|\\bveridian\\b|\\bveridium\\b|\\bverran\\b|\\bvespera\\b|\\bvexar\\b|\\bveyl\\b|\\bveyn\\b|\\bveyne\\b|\\bveyra\\b|\\bveyth\\b|\\bvial\\b|\\bvibrant\\b|\\bvibrated\\b|\\bviewport\\b|\\bviewscreen\\b|\\bvolkov\\b|\\bvorath\\b|\\bvorlag\\b|\\bvorn\\b|\\bvorne\\b|\\bvoryn\\b|\\bvoss\\b|\\bvrook\\b|\\bvrykali\\b|\\bvrynn\\b|\\bwafted\\b|\\bwailed\\b|\\bwarily\\b|\\bwariness\\b|\\bwarred\\b|\\bwavered\\b|\\bwavering\\b|\\bweariness\\b|\\bweathered\\b|\\bwelled\\b|\\bwheezed\\b|\\bwhimpered\\b|\\bwhir\\b|\\bwhirled\\b|\\bwhirred\\b|\\bwhirring\\b|\\bwhirs\\b|\\bwhisper\\b|\\bwhispered\\b|\\bwhispering\\b|\\bwhispers\\b|\\bwhisperwind\\b|\\bwhisperwood\\b|\\bwhiterun\\b|\\bwidened\\b|\\bwinced\\b|\\bwincing\\b|\\bwindowpane\\b|\\bwindowpanes\\b|\\bwizened\\b|\\bwojek\\b|\\bwoodsmoke\\b|\\bwrithe\\b|\\bwrithed\\b|\\bwritingprompts\\b|\\bxandros\\b|\\bxanthean\\b|\\bxantheans\\b|\\bxaphan\\b|\\bxaren\\b|\\bxarpti\\b|\\bxavius\\b|\\bxendari\\b|\\bxenobiologist\\b|\\bxenobiology\\b|\\bxenolinguist\\b|\\bxenos\\b|\\bxeridian\\b|\\bxeridians\\b|\\bxhk'kht\\b|\\bxyla\\b|\\bxylar\\b|\\bxylara\\b|\\bxylia\\b|\\bxylo\\b|\\bxylons\\b|\\bxylophia\\b|\\bxylos\\b|\\bxylosian\\b|\\bxylosians\\b|\\bxylossian\\b|\\bxylossians\\b|\\bxyloth\\b|\\bxylothian\\b|\\bxylothians\\b|\\bxylox\\b|\\bxyra\\b|\\by'lgoth\\b|\\byawned\\b|\\byearned\\b|\\byellowed\\b|\\byelped\\b|\\byowled\\b|\\bzafir\\b|\\bzalrex\\b|\\bzarek\\b|\\bzarthus\\b|\\bzephyr\\b|\\bzephyra\\b|\\bzephyria\\b|\\bzephyrian\\b|\\bzephyrians\\b|\\bzephyrion\\b|\\bzephyros\\b|\\bzephyrus\\b|\\bzetans\\b|\\bzha'thik\\b|\\bzhra'gha\\b|\\bzorath\\b|\\bzorax\\b|\\bzoraxians\\b|\\bzorgon\\b|\\bzorp\\b|\\bzorvath\\b|\\bzorvathian\\b|\\bzorvathians\\b|\\bzydonian\\b|\\bzydonians\\b|\\bzyla\\b|\\bzylar\\b|\\bzylara\\b|\\bzyloth\\b|\\bzylth\\b|\\bzyn\\b|\\bzyn'thari\\b|\\bzyn'thra\\b|\\bzyra\\b|\\bzz'glorg\\b|\\bsaid voice\\b|\\bdeep breath\\b|\\bvoice barely\\b|\\bcould help\\b|\\basked voice\\b|\\bbarely whisper\\b|\\bheart pounding\\b|\\btook deep\\b|\\bfelt like\\b|\\bmind racing\\b|\\bcould feel\\b|\\bfind way\\b|\\bair thick\\b|\\bvoice low\\b|\\beyes wide\\b|\\bstepped forward\\b|\\bshook head\\b|\\bvoice steady\\b|\\bmade way\\b|\\bcould see\\b|\\beyes widened\\b|\\bhelp feel\\b|\\bfirst time\\b|\\bbrow furrowed\\b|\\bvoice trembling\\b|\\bpounding chest\\b|\\bsomething else\\b|\\bclosed eyes\\b|\\beyes filled\\b|\\bfelt surge\\b|\\beyes narrowed\\b|\\bshake feeling\\b|\\bdimly lit\\b|\\bwhispered voice\\b|\\bcasting long\\b|\\bfelt sense\\b|\\bfelt strange\\b|\\bmind raced\\b|\\bbarely audible\\b|\\bcould shake\\b|\\bheart racing\\b|\\beyes fixed\\b|\\bheart raced\\b|\\bworld around\\b|\\byoung woman\\b|\\beyes scanning\\b|\\bknew would\\b|\\bfeel sense\\b|\\blong shadows\\b|\\bsense unease\\b|\\bwould never\\b|\\bthick scent\\b|\\bsense purpose\\b|\\brun spine\\b|\\bshadows across\\b|\\blooked around\\b|\\breplied voice\\b|\\bone day\\b|\\bvoice laced\\b|\\bleaned forward\\b|\\bfell silent\\b|\\bvoice filled\\b|\\bknew could\\b|\\bacross face\\b|\\bvoice echoing\\b|\\bstark contrast\\b|\\bmake sense\\b|\\blay ahead\\b|\\bhelp wonder\\b|\\byoung man\\b|\\blooked eyes\\b|\\btook step\\b|\\bhung air\\b|\\braised hand\\b|\\bopened eyes\\b|\\bsun dipped\\b|\\bleaned back\\b|\\bone thing\\b|\\blet go\\b|\\bgaze fixed\\b|\\braised eyebrow\\b|\\bliving room\\b|\\beyes narrowing\\b|\\bold man\\b|\\bdim light\\b|\\btilted head\\b|\\bstumbled upon\\b|\\bswallowed hard\\b|\\bflicker something\\b|\\bready face\\b|\\bdeep within\\b|\\blooked like\\b|\\bsomething far\\b|\\bcould hear\\b|\\bnever seen\\b|\\bgrowing sense\\b|\\bsmile playing\\b|\\bstrange sense\\b|\\bbegan voice\\b|\\blet us\\b|\\bever seen\\b|\\balmost imperceptible\\b|\\bconstant reminder\\b|\\bdipped horizon\\b|\\bunlike anything\\b|\\balso knew\\b|\\bplaying lips\\b|\\bmaybe maybe\\b|\\bsound like\\b|\\bfelt chill\\b|\\blong time\\b|\\bvoice soft\\b|\\bfilled air\\b|\\bhorizon casting\\b|\\byears ago\\b|\\bvoice tinged\\b|\\bfluorescent lights\\b|\\bback chair\\b|\\bglimmer hope\\b|\\bfelt weight\\b|\\bbeneath feet\\b|\\bvoice firm\\b|\\bone one\\b|\\bleaving behind\\b|\\bdays turned\\b|\\bheart pounded\\b|\\baround room\\b|\\bwould find\\b|\\bmixture fear\\b|\\bcaught eye\\b|\\bdark lord\\b|\\bvoice dripping\\b|\\bstepped closer\\b|\\bair crackled\\b|\\bfabric reality\\b|\\bcaught throat\\b|\\bheld breath\\b|\\bface whatever\\b|\\bface etched\\b|\\bfigure emerged\\b|\\bnodded eyes\\b|\\btrembling slightly\\b|\\bair around\\b|\\bchill run\\b|\\bspreading across\\b|\\bturned weeks\\b|\\bsense dread\\b|\\bnew world\\b|\\beyes darting\\b|\\bsense peace\\b|\\bmind reeling\\b|\\beyes gleaming\\b|\\bleft behind\\b|\\bsomething akin\\b|\\btrying make\\b|\\bone would\\b|\\bopened mouth\\b|\\bsaid eyes\\b|\\bvoice echoed\\b|\\bface pale\\b|\\bvoice like\\b|\\bway back\\b|\\bcould quite\\b|\\banything ever\\b|\\blike eternity\\b|\\bone could\\b|\\blong since\\b|\\beyes locked\\b|\\bbreath caught\\b|\\bbeneath surface\\b|\\bwalked away\\b|\\bechoed mind\\b|\\bbeacon hope\\b|\\bcasting warm\\b|\\blet get\\b|\\bstep forward\\b|\\bchapter seven\\b|\\bmake sure\\b|\\bcarefully constructed\\b|\\bturned face\\b|\\bspoke voice\\b|\\bfaces etched\\b|\\beyes widening\\b|\\bforward eyes\\b|\\btrying keep\\b|\\bcleared throat\\b|\\bcould find\\b|\\bturned back\\b|\\blet see\\b|\\bfelt shiver\\b|\\bcalled voice\\b|\\bworld outside\\b|\\bnext morning\\b|\\belara felt\\b|\\bfelt different\\b|\\bhesitated moment\\b|\\bfelt familiar\\b|\\bshiver run\\b|\\bman named\\b|\\bacross room\\b|\\bvoice barely whisper\\b|\\btook deep breath\\b|\\bcould help feel\\b|\\bheart pounding chest\\b|\\bsaid voice barely\\b|\\bhelp feel sense\\b|\\bsaid voice low\\b|\\bvoice barely audible\\b|\\basked voice barely\\b|\\bcould shake feeling\\b|\\bcasting long shadows\\b|\\bcould help wonder\\b|\\bsaid voice steady\\b|\\bair thick scent\\b|\\blong shadows across\\b|\\bsun dipped horizon\\b|\\bsmile playing lips\\b|\\bdays turned weeks\\b|\\bchill run spine\\b|\\bfelt chill run\\b|\\bwhispered voice barely\\b|\\bfelt like eternity\\b|\\bshiver run spine\\b|\\bsaid voice filled\\b|\\bspreading across face\\b|\\bleaned back chair\\b|\\bvoice steady despite\\b|\\bunlike anything ever\\b|\\bfelt shiver run\\b|\\btaking deep breath\\b|\\bbreath caught throat\\b|\\bready face whatever\\b|\\bheart pounded chest\\b|\\broom fell silent\\b|\\btrying make sense\\b|\\bdipped horizon casting\\b|\\bsaid voice trembling\\b|\\bsomething else something\\b|\\bdeep breath trying\\b|\\basked voice trembling\\b|\\bcould feel weight\\b|\\bsaid voice firm\\b|\\bfelt strange sense\\b|\\bwords hung air\\b|\\bbrow furrowed concentration\\b|\\bchallenges lay ahead\\b|\\bsomething else entirely\\b|\\bvoice low rumble\\b|\\bsun began set\\b|\\bsent shiver spine\\b|\\bend end end\\b|\\bvoice trembling slightly\\b|\\beyes never leaving\\b|\\bgrowing sense unease\\b|\\bdoor creaked open\\b|\\bshake feeling something\\b|\\bair hung thick\\b|\\bheart skipped beat\\b|\\bmade way back\\b|\\btook step back\\b|\\brain continued fall\\b|\\bsun hung low\\b|\\bsaid voice dripping\\b|\\bsaid voice soft\\b|\\bcasting warm glow\\b|\\btook step forward\\b|\\beyes wide fear\\b|\\brenewed sense purpose\\b|\\bwould find way\\b|\\btrying keep voice\\b|\\bhung low sky\\b|\\bhorizon casting long\\b|\\bsmile spreading across\\b|\\bleaned forward eyes\\b|\\banything ever seen\\b|\\bone thing certain\\b|\\bmind racing possibilities\\b|\\blow sky casting\\b|\\bsaid voice laced\\b|\\bheart hammered ribs\\b|\\bhung heavy air\\b|\\blooked eyes filled\\b|\\bface whatever challenges\\b|\\btook step closer\\b|\\beyes filled mixture\\b|\\broad ahead would\\b|\\bspread like wildfire\\b|\\bwhispered voice trembling\\b|\\bfelt sense peace\\b|\\bhung air heavy\\b|\\bair thick tension\\b|\\bnewfound sense purpose\\b|\\bflicker something akin\\b|\\bgrin spreading across\\b|\\bdeep breath stepped\\b|\\bdoor swung open\\b|\\bknew would never\\b|\\beyes locked onto\\b|\\btried make sense\\b|\\bdust motes danced\\b|\\bdimly lit room\\b|\\bsmall intricately carved\\b|\\bbrow furrowed confusion\\b|\\bdeep breath steeling\\b|\\bcould help notice\\b|\\bone last time\\b|\\beyes darting around\\b|\\bsent shivers spine\\b|\\bkeep voice steady\\b|\\byoung woman named\\b|\\bsaid voice tinged\\b|\\bpainting sky hues\\b|\\beyes wide wonder\\b|\\bnodded mind racing\\b|\\bfingers flying across\\b|\\bwhatever challenges lay\\b|\\bfigure emerged shadows\\b|\\bmind raced trying\\b|\\bknew road ahead\\b|\\braised hand silencing\\b|\\bpiercing blue eyes\\b|\\bfelt strange sensation\\b|\\bturned walked away\\b|\\bsaid voice calm\\b|\\bsmall smile playing\\b|\\bfelt cold dread\\b|\\bmind racing questions\\b|\\bcould find way\\b|\\bspread across face\\b|\\bfirst time long\\b|\\bground beneath feet\\b|\\bhung thick scent\\b|\\bsky casting long\\b|\\bmind racing implications\\b|\\bweeks weeks months\\b|\\basked voice low\\b|\\bchill ran spine\\b|\\bsaid trying sound\\b|\\bwould never forget\\b|\\bgaze sweeping across\\b|\\basked voice laced\\b|\\bshiver ran spine\\b|\\bturned weeks weeks\\b|\\bspent countless hours\\b|\\bbrow furrowed concern\\b|\\beyes wide mixture\\b|\\bresonated deep within\\b|\\beyes widened surprise\\b|\\bair thick anticipation\\b|\\bbreath catching throat\\b|\\bmind racing tried\\b|\\bdeep breath feeling\\b|\\blooked around room\\b|\\bshook head trying\\b|\\bwhatever lay ahead\\b|\\bsaid voice like\\b|\\breplied voice steady\\b|\\beyes scanning room\\b|\\bfelt growing sense\\b|\\bstepped forward voice\\b|\\bnever seen anything\\b|\\bstammered voice barely\\b|\\bhelp feel twinge\\b|\\bknew one thing\\b|\\bstepped forward eyes\\b|\\bsmile spread across\\b|\\bmaybe maybe could\\b|\\bfeel sense unease\\b|\\bseen anything like\\b|\\bknew chilling certainty\\b|\\bgrowing sense dread\\b|\\bintricately carved wooden\\b|\\bheart heavy weight\\b|\\bwords echoed mind\\b|\\bsighed running hand\\b|\\bscent damp earth\\b|\\bair thick smell\\b|\\bsaid voice smooth\\b|\\bbegan set casting\\b|\\bblood ran cold\\b|\\bsaid voice echoing\\b|\\bhand instinctively reaching\\b|\\bsense peace wash\\b|\\belara said voice\\b|\\bsmile tugging corners\\b|\\bsaid voice tight\\b|\\bcould feel power\\b|\\beyes wide terror\\b|\\bmind already racing\\b|\\bknuckles turning white\\b|\\bfelt glimmer hope\\b|\\bmade decision would\\b|\\bfaint almost imperceptible\\b|\\beyes widened shock\\b|\\bfeel sense pride\\b|\\btears streaming face\\b|\\bhorizon painting sky\\b|\\bcasting eerie glow\\b|\\blong could remember\\b|\\bcontinued fall washing\\b)",
]
COMPILED_REGEX_PATTERNS = [re.compile(pattern) for pattern in REGEX_PATTERNS]
