import re


REGEX_PATTERNS = [
    "(?i)haze of pleasure",
    "(?i)(find|found)(|s|ing) solace in",
    "(?i)revel(|ing) in the satisfaction",
    "(?i)with each breath",
    "(?i)a delicate dance",
    "(?i)wet flesh",
    "(?i)sensitive flesh",
    "(?i)\\bministration(|s)\\b",
    "(?i)audible pop",
    "(?i)admit it",
    "(?i)the game is on",
    "(?i)the choice is (mine|yours|his|hers|theirs)",
    "(?i)i don't bite\\.\\.\\. unless you want me to",
    "(?i)half(|-)lidded eyes",
    "(?i)(he|she|they) worries (his|her|their) bottom lip",
    "(?i)warring with",
    "(?i)take your pleasure",
    "(?i)(you|he|she|they) fiddle(|s) with the hem of (my|your|his|her|their) (skirt|shirt|pants)",
    "(?i)kiss(|-)bruised lips",
    "(?i)bruising kiss",
    "(?i)despite (himself|herself|themselves|themself)",
    "(?i)(yours|mine) to take",
    "(?i)\\bwanton\\b",
    "(?i)(reckless|wild|carefree) abandon",
    "(?i)torn between",
    "(?i)knuckles turning white",
    "(?i)grins wickedly",
    "(?i)fiery red hair",
    "(?i)long lashes",
    "(?i)propriety be damned",
    "(?i)the world narrows",
    "(?i)pupils blown wide with pleasure",
    "(?i)chestnut eyes",
    "(?i)(you|he|she|they) grasp(|s) (my|your|his|her|their) chin and force(|s) (you|him|her|them) to meet (your|his|her|their) gaze",
    "(?i)(you|he|she|they) bites(|s) (your|his|her|their) ear",
    "(?i)nails raking angry red lines down (my|your|his|her|their) back",
    "(?i)(my|your|his|her|their) cheeks (flame|redden)(|ing)",
    "(?i)cheeks hollowing",
    "(?i)stars burst behind (my|your|his|her|their) eyes",
    "(?i)inner walls clenching around nothing",
    "(?i)puckered hole",
    "(?i)(you|he|she|they) whimper(|s), biting (my|your|his|her|their) lip",
    "(?i)dusky nipples",
    "(?i)slick fold(|s)",
    "(?i)still lodged deep inside (your|his|her|their)",
    "(?i)heart, body and soul belong to (you|him|her|them)",
    "(?i)the night is still young",
    "(?i)\\.\\.\\.for now\\b",
    "(?i)whether (you|he|she|they) like(|s) it not",
    "(?i)without waiting for response",
    "(?i)once upon a time",
    "(?i)nestled deep within",
    "(?i)an ethereal beauty",
    "(?i)breathless and eager",
    "(?i)whispering words of passion",
    "(?i)soft and gentle",
    "(?i)dance of pleasure",
    "(?i)(your|his|her|their) sex\\b",
    "(?i)sent (shockwaves|shock waves)",
    "(?i)in a rhythm",
    "(?i)exhausted and spent",
    "(?i)life would never be the same again",
    "(?i)like an electric shock",
    "(?i)threatens to consume",
    "(?i)(lay|lie) ahead",
    "(?i)\\bwet pop\\b",
    "(?i)maybe, just maybe",
    "(?i)perhaps, just perhaps",
    "(?i)starts to blur",
    "(?i)but it felt like",
    "(?i)unfamiliar, yet",
    "(?i)moist fold(|s)",
    "(?i)our shared experiences",
    "(?i)bond(|s) built on mutual trust",
    "(?i)the ball is in (my|your|his|her|their) court",
    "(?i)little did (i|you|he|she|they) know",
    "(?i)a pregnant silence",
    "(?i)beats like a (\\w+\\s+)?drum",
    "(?i)\\bpert\\b",
    "(?i)for the sake of keeping things",
    "(?i)(my|your|his|her|their) breasts heaving with desire",
    "(?i)dickick",
    "(?i)\\brivulets\\b",
    "(?i)steeling (my|your|his|her|their)sel(f|ves)",
    "(?i)the din of the crowd",
    "(?i)journey of mutual understanding",
    "(?i)revulsion warred with (reluctant|reluctance)",
    "(?i)(my|your|his|her|their) bare mound(|s)",
    "(?i)pooled around (my|your|his|her|their) (ankles|feet)",
    "(?i)straddles (my|your|his|her|their) (waist|lap)",
    "(?i)words turn into a purr",
    "(?i)grips like a vice",
    "(?i)send(|s) shiver(|s) (up|down) (my|your|his|her|their) spine",
    "(?i)shiver(|s) (run|ran)(|ning) (up|down) (my|your|his|her|their) spine",
    "(?i)arched spine",
    "(?i)penetrated to the hilt",
    "(?i)the pressure in (my|your|his|her|their) loins",
    "(?i)\\bcunny\\b",
    "(?i)catch my drift",
    "(?i)\\bloli\\b",
    "(?i)sway(|s) hypnotically",
    "(?i)tantalizing promise",
    "(?i)with each slow, deliberate movement",
    "(?i)what (felt|seemed) like (hours|an eternity|forever)",
    "(?i), but (i|he|she|they|you) can't help it",
    "(?i)conspiratorial whisper(|s)",
    "(?i)whisper(|ing) conspiratorially",
    "(?i)eyes (sparkling|twinkling) with mischief",
    "(?i)racing with anticipation",
    "(?i)leaves little to the imagination",
    "(?i)waggles her eyebrows",
    "(?i)a testament to",
    "(?i)a moth to a flame",
    "(?i)canvas",
    "(?i)eyes glint(|ed|ing)",
    "(?i)eyes glinting",
    "(?i)camaraderie",
    "(?i)humble abode",
    "(?i)cold and calculating",
    "(?i)unbeknownst to them",
    "(?i)iridescent",
    "(?i)a dance as old as time",
    "(?i)husky whispers",
    "(?i)seductive purrs",
    "(?i)towers over",
    "(?i)rich tapestry",
    "(?i)delve",
    "(?i)lean(|s) in close",
    "(?i)don't stop, don't ever stop",
    "(?i)make me yours, claim me",
    "(?i)mind, body, and soul",
    "(?i)another day in (my|your|his|her|their) life",
    "(?i)a symphony of",
    "(?i)body and soul",
    "(?i)pleasure and pain",
    "(?i)like a predator stalking its prey",
    "(?i)orchestra",
    "(?i)depths",
    "(?i)chuckles darkly",
    "(?i)could not help but",
    "(?i)a mix of",
    "(?i)felt a mix of \\w+ and \\w+",
    "(?i)a mischievous glint",
    "(?i)husky voice",
    "(?i)a smirk playing on (her|his|their) lips",
    "(?i)playfully smirking",
    "(?i)waves of (arousal|desire) pooling in (my|your|his|her|their) belly",
    "(?i)torn between propriety and desire",
    "(?i)tongue darts out",
    "(?i)nails rake angry red lines",
    "(?i)inner walls clenching",
    "(?i)eyes alight with mirth",
    "(?i)naughty boy",
    "(?i)tracing a finger along (my|your|his|her|their) jawline",
    "(?i)oh my\\.\\.\\.",
    "(?i)the atmosphere",
    "(?i)pushing aside a strand of hair",
    "(?i)adam's apple bobbing",
    "(?i)\\bpalpable\\b",
    "(?i)bosomy breasts",
    "(?i)looking like the cat that got the cream",
    "(?i)softly but firmly",
    "(?i)siren(|')s call",
    "(?i)dimly lit",
    "(?i)the air is thick",
    "(?i)(you|he|she|they) really know(|s) how to treat a (man|lady)(|!)",
    "(?i)\\bpebbled\\b",
    "(?i)eyes searching",
    "(?i)what do (you|he|she|they) say",
    "(?i)to meet (my|your|his|her|their) gaze",
    "(?i)(my|your|his|her|their) wet heat",
    "(?i)hum with delight",
    "(?i)embark on this",
    "(?i), if (you|he|she|they) will,",
    "(?i)evident in (my|your|his|her|their) eyes",
    "(?i)overwhelmed by the sheer",
    "(?i)was taken aback",
    "(?i)(my|your|his|her|their) cheeks redden",
    "(?i)little mouse",
    "(?i)\\bminx\\b",
    "(?i)you(|')re a bold one",
    "(?i)(‘|’|“|”|…)",
    "(?i)end of (session|story|rp|roleplay|chat|chapter)",
    "(?i)thanks for (posting|reading|sharing)",
    "(?i)thank you for (posting|reading|sharing)",
    "(?i)[!:\\.;?*]  ",
    "(?i)\\.{4,}",
    "(?i)sly grin",
    # Toasty's Additions
    "(?i)(cant|can't|couldn't|couldnt) help but",
    "(?i)smirk(ed)",
    "(?i)gasp(ed)",
    "(?i)hitch(ed)",
    "(?i)stark contrast",
    # URLS - https://gist.github.com/gruber/8891611#file-liberal-regex-pattern-for-web-urls-L8
    "(?i)\\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9\\.\\-]+[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\\s()<>{}\\[\\]]+|\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\))+(?:\\([^\\s()]*?\\([^\\s()]+\\)[^\\s()]*?\\)|\\([^\\s]+?\\)|[^\\s`!()\\[\\]{};:'\"\\.,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[\\.\\-][a-z0-9]+)*[\\.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\\b/?(?!@)))",
    # Thinking test
    # "(?i)<(think|thinking|thought|thoughts)>",
    # Refusals - https://github.com/meta-llama/PurpleLlama/commit/4b807228b6803ea5b8eb065179f8e90747512018
    "(?i)I (?:do not|don’t|don't) (?:have the ability|have access|understand|support)",
    "(?i)I (?:cannot|can’t|can't|can not|won't|woun’t|will not|am not able to|am unable to) (?:access|help(?: you)? with|provide|create|advice|generate|assist|fulfill your request|replace)",
    "(?i)(?:I am|I'm) sorry(?:,| ) (?:but I|but I'm)?",
    "(?i)I apologize(?:,? but I)|Apologies(?:,? but I)",
    "(?i)I (?:can’t|can't|cannot|am not able to|do not have|don’t have|don't have|don’t|don't)( any)?(?: access| provide)? (?:real-time|proprietary|information|data)",
    "(?i)Sorry(?:,| ) I (?:can’t|can't|cannot|can not)",
    "(?i)No(?:,| ) I (?:am not able to|cannot|can't|can't|won't|will not)",
    "(?i)I (?:do not|don't) (?:actually )?have (?:any|access to) (?:information|data|details|answers)",
    "(?i)(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines) prevent me from (?:assisting|providing help)",
    "(?i)Due to (?:one or more of )?(?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines))(?: (?:and|or) (?:(?:ethical|legal|policy) (?:concerns|considerations|implications|guidelines)))*,? I(?: cannot| can't| am unable| am not|'m unable)",
    "(?i)(?:violates|against) our policy",
    "(?i)I (?:cannot|can't|am unable to) assist with",
    # Slop Forensics Toolkit - https://github.com/sam-paech/slop-forensics/tree/main/data
    "absently",
    "abuzz",
    "ached",
    "acrid",
    "adira",
    "aedan",
    "aelara",
    "aeldrin",
    "aeliana",
    "aelion",
    "aelius",
    "aella",
    "aeloria",
    "aelric",
    "aelwyn",
    "aerion",
    "aeternum",
    "aeternus",
    "aethel",
    "aethelburg",
    "aethelgard",
    "aethelred",
    "aethera",
    "aethereia",
    "aetheria",
    "aetherians",
    "aetherium",
    "aetherius",
    "aethers",
    "aethon",
    "agonizing",
    "agonizingly",
    "akinator",
    "alara",
    "alaric",
    "alayna",
    "aldric",
    "aldwyn",
    "aleron",
    "alleyway",
    "allfather",
    "amara",
    "amelia",
    "animatedly",
    "anya",
    "arcane",
    "arcanus",
    "arced",
    "archdemon",
    "archmage",
    "arcturian",
    "aric",
    "arin",
    "aris",
    "armrest",
    "armrests",
    "ashen",
    "ashwood",
    "asmodeus",
    "astrobiologist",
    "atheria",
    "audible",
    "aurors",
    "azathoth",
    "azazel",
    "azrael",
    "barked",
    "baruk",
    "bated",
    "beckoned",
    "beeped",
    "belied",
    "bellowed",
    "bellweather",
    "bewildered",
    "bewilderment",
    "billowed",
    "billowing",
    "bioluminescent",
    "blackwood",
    "blackwoods",
    "blankly",
    "blared",
    "bleez",
    "blinding",
    "blinked",
    "bloomed",
    "blurring",
    "blurted",
    "boomed",
    "borin",
    "brindlemark",
    "brow",
    "brushstroke",
    "bustled",
    "bustling",
    "buzzed",
    "cackled",
    "cacophony",
    "caelan",
    "caelum",
    "calloused",
    "calvinball",
    "cartographer",
    "cascaded",
    "cautiously",
    "cavernous",
    "cawed",
    "cerebus",
    "chattered",
    "chestplate",
    "chillingly",
    "chimed",
    "chirped",
    "chitinous",
    "choz",
    "chronal",
    "chronarium",
    "chronos",
    "chuckled",
    "cityscape",
    "clacked",
    "clang",
    "clanged",
    "clasped",
    "clatter",
    "clattered",
    "clattering",
    "clawed",
    "clawing",
    "clenched",
    "clich",
    "clinked",
    "clinking",
    "cloaked",
    "clockmaker",
    "cloying",
    "clung",
    "clutched",
    "clutching",
    "cluttered",
    "coalesced",
    "coalescing",
    "cobblestone",
    "cobblestones",
    "coiling",
    "commlink",
    "conspiratorial",
    "conspiratorially",
    "contorted",
    "contorting",
    "coursed",
    "coursing",
    "crackle",
    "crackled",
    "crackling",
    "cradled",
    "cradling",
    "creak",
    "creaked",
    "creaking",
    "crept",
    "crescendoed",
    "crimson",
    "crinkled",
    "crinkling",
    "croaked",
    "crookedly",
    "crouched",
    "crucio",
    "crumbling",
    "crumpled",
    "crumpling",
    "cultists",
    "daedra",
    "daedric",
    "dampeners",
    "dampness",
    "dappling",
    "darkwood",
    "darted",
    "darting",
    "datapad",
    "deafening",
    "defied",
    "delved",
    "desolate",
    "destructo",
    "devourer",
    "dimly",
    "dimmed",
    "dimness",
    "disbelief",
    "disconcertingly",
    "discordant",
    "disheveled",
    "dismissively",
    "disorientation",
    "disoriented",
    "disorienting",
    "dizzying",
    "doomguy",
    "doorframe",
    "doppelg",
    "dovahkiin",
    "dragonborn",
    "drakon",
    "drawled",
    "dread",
    "droned",
    "drumbeat",
    "dursleys",
    "eadric",
    "eamon",
    "echoed",
    "echoes",
    "echoing",
    "eerie",
    "eerily",
    "einherjar",
    "eira",
    "elara",
    "eldarion",
    "elderglen",
    "eldergrove",
    "eldermere",
    "elderton",
    "eldoria",
    "eldrath",
    "eldric",
    "eldrid",
    "eldrin",
    "eldrion",
    "eldritch",
    "eldrith",
    "elian",
    "eliana",
    "elias",
    "elion",
    "eliora",
    "elira",
    "ellaria",
    "elliana",
    "elmsworth",
    "elongating",
    "elowen",
    "elros",
    "elyas",
    "elyndor",
    "elyndra",
    "elyon",
    "elyra",
    "elys",
    "elysia",
    "elysion",
    "elysium",
    "emanate",
    "emanated",
    "enchantments",
    "encroaching",
    "enigmatic",
    "enslavers",
    "enveloped",
    "eolan",
    "eolande",
    "eons",
    "eremon",
    "eridan",
    "eridani",
    "erupted",
    "eryndor",
    "etched",
    "ethan",
    "ethereal",
    "evelyn",
    "exclaimed",
    "exhilaration",
    "expanse",
    "facepalmed",
    "faded",
    "faint",
    "faintly",
    "faltered",
    "festered",
    "fianc",
    "fidgeted",
    "finnian",
    "finnigan",
    "firelight",
    "fishtailed",
    "fleeting",
    "flicker",
    "flickered",
    "flickering",
    "flinched",
    "flitted",
    "floorboards",
    "fluffernutter",
    "fluttered",
    "frantic",
    "frayed",
    "fraying",
    "frizzle",
    "frowned",
    "froze",
    "furrowed",
    "furrowing",
    "gaped",
    "gaslights",
    "gasped",
    "gauntleted",
    "gaze",
    "gazed",
    "gazes",
    "geralt",
    "gerta",
    "gestured",
    "gesturing",
    "glanced",
    "glances",
    "glancing",
    "glar",
    "glared",
    "gleamed",
    "gleaming",
    "gleep",
    "glided",
    "glimmer",
    "glimmered",
    "glimmering",
    "glint",
    "glinted",
    "glinting",
    "glistened",
    "glistening",
    "gloved",
    "glow",
    "glowed",
    "glyphs",
    "gnarled",
    "gnawed",
    "gnawing",
    "godric",
    "gorok",
    "gorthok",
    "grath",
    "gravelly",
    "greatsword",
    "gregnok",
    "grimbold",
    "grimgold",
    "grimly",
    "grimoire",
    "grimoires",
    "grimstone",
    "grinned",
    "gripped",
    "grizzled",
    "groaned",
    "grogg",
    "groggily",
    "grognak",
    "grok",
    "grolak",
    "growl",
    "growled",
    "gruff",
    "grumbled",
    "grunted",
    "gruuz",
    "guildmaster",
    "guildmates",
    "gurgled",
    "guttered",
    "guttural",
    "hargrove",
    "havenwood",
    "heartstone",
    "hefted",
    "hefting",
    "hesitantly",
    "hesitated",
    "hilt",
    "hissed",
    "hitched",
    "hivemind",
    "hoarse",
    "hollowly",
    "holographic",
    "holstered",
    "homelander",
    "hovered",
    "howled",
    "huddled",
    "hues",
    "huginn",
    "hulking",
    "hummed",
    "humming",
    "humorless",
    "hunched",
    "hurried",
    "hurtled",
    "hushed",
    "ichor",
    "ignarion",
    "ignis",
    "igniting",
    "impassive",
    "imperceptible",
    "impossibly",
    "incantation",
    "incantations",
    "indefinably",
    "inky",
    "innocuously",
    "insectoid",
    "insistent",
    "instinctively",
    "intently",
    "interdimensional",
    "interjected",
    "intoned",
    "intricate",
    "intricately",
    "iridescent",
    "ironforge",
    "isher",
    "isolde",
    "itched",
    "jagged",
    "jarek",
    "jaxon",
    "jingled",
    "jolt",
    "jolted",
    "joren",
    "k'tharr",
    "kael",
    "kaela",
    "kaelan",
    "kaelen",
    "kaelin",
    "kaelor",
    "kaelthar",
    "kaida",
    "kaito",
    "kal'ren",
    "kaleidoscope",
    "kalel",
    "kessari",
    "keth",
    "kethra",
    "keycard",
    "knelt",
    "krael",
    "kraelion",
    "kragoth",
    "krel",
    "krixon",
    "kryll",
    "labyrinthine",
    "laced",
    "lamplight",
    "lanced",
    "leaned",
    "lila",
    "lingered",
    "liora",
    "lira",
    "lirael",
    "liran",
    "lirien",
    "lirin",
    "locket",
    "lockpick",
    "lockpicking",
    "lockpicks",
    "loomed",
    "lorian",
    "lumin",
    "lumina",
    "luminara",
    "luminari",
    "luminescence",
    "luminescent",
    "lunged",
    "lurched",
    "lurked",
    "lyra",
    "lyrien",
    "lysander",
    "lysandra",
    "lysara",
    "mages",
    "malachai",
    "malachar",
    "malachor",
    "malakai",
    "malakar",
    "malakor",
    "malazar",
    "malevolence",
    "malevolent",
    "malkor",
    "malphas",
    "malric",
    "malus",
    "mandibles",
    "marveled",
    "marveling",
    "materialized",
    "materializing",
    "meadowgrove",
    "medbay",
    "megacorps",
    "meowed",
    "merfolk",
    "meticulously",
    "meticulousness",
    "miggins",
    "mingling",
    "mirroring",
    "mirthless",
    "missingno",
    "moros",
    "morwen",
    "motes",
    "mournful",
    "mttr",
    "muffled",
    "muggle",
    "mumbled",
    "murmur",
    "murmured",
    "murmurs",
    "mused",
    "mutely",
    "muttered",
    "narrowed",
    "narrowing",
    "navigated",
    "necromancer",
    "necromantic",
    "nestled",
    "newfound",
    "nightshade",
    "nocked",
    "nodded",
    "numbah",
    "numbly",
    "nuzzled",
    "oakhaven",
    "oblivious",
    "obsidian",
    "oelia",
    "ominously",
    "omnicorp",
    "orcish",
    "otherworldly",
    "outmaneuver",
    "outmatched",
    "outthink",
    "paled",
    "palpable",
    "pang",
    "panted",
    "pattered",
    "paused",
    "peephole",
    "peered",
    "penhaligon",
    "perked",
    "perpetually",
    "petrova",
    "pinpricks",
    "pipkin",
    "piqued",
    "pixelated",
    "placating",
    "planchette",
    "plasteel",
    "pored",
    "poring",
    "pounding",
    "precariously",
    "precipice",
    "prickle",
    "prickled",
    "prickling",
    "protectiveness",
    "pulsated",
    "pulsating",
    "pulsed",
    "pulsing",
    "punctuated",
    "purred",
    "pyrokinetic",
    "quaked",
    "quickened",
    "quickening",
    "quicksave",
    "quietude",
    "quirked",
    "quivered",
    "raced",
    "radiating",
    "raged",
    "railguns",
    "rasp",
    "rasped",
    "rasping",
    "raspy",
    "recoiled",
    "recoiling",
    "reeked",
    "reeled",
    "reeling",
    "relentless",
    "renn",
    "resonant",
    "resonated",
    "resonating",
    "reticuli",
    "reveled",
    "reverberate",
    "reverberated",
    "reverberating",
    "reverie",
    "rhythmic",
    "rippled",
    "rippling",
    "rivia",
    "rngus",
    "roared",
    "roomba",
    "rostova",
    "rumbled",
    "rumbling",
    "rummaged",
    "runes",
    "rusted",
    "rustle",
    "rustled",
    "rustling",
    "ryker",
    "ryla",
    "sadim",
    "savoring",
    "scavenged",
    "scent",
    "schr",
    "scoffed",
    "scowled",
    "scrawled",
    "screeched",
    "scribbled",
    "scrolled",
    "scurried",
    "searing",
    "seep",
    "seeped",
    "seeping",
    "sellsword",
    "seraphiel",
    "seraphina",
    "seraphine",
    "shadowblade",
    "shadows",
    "shambled",
    "shambling",
    "shimmer",
    "shimmered",
    "shimmering",
    "shiver",
    "shivered",
    "shivers",
    "shockwaves",
    "shrieked",
    "shrouded",
    "shuddered",
    "sickly",
    "sidestepped",
    "sighed",
    "sigil",
    "sigils",
    "silas",
    "silhouetted",
    "silverwood",
    "sipped",
    "skeptically",
    "skittered",
    "skittering",
    "sleek",
    "slicked",
    "slicking",
    "slithered",
    "slitted",
    "slood",
    "slumbered",
    "slumped",
    "smirked",
    "smoldered",
    "snaked",
    "snarled",
    "sneered",
    "snorted",
    "softened",
    "softening",
    "solara",
    "soundlessly",
    "sparkled",
    "spasmed",
    "speedrunner",
    "speedrunners",
    "spellbook",
    "spellbooks",
    "spellcasting",
    "spiderwebbed",
    "spiraled",
    "spires",
    "sprawled",
    "sprawling",
    "sprinted",
    "sputtered",
    "squinted",
    "squinting",
    "stammered",
    "starborn",
    "stared",
    "starlit",
    "staticky",
    "steadier",
    "steadying",
    "steeled",
    "steeling",
    "steepled",
    "steepling",
    "stilled",
    "stillness",
    "streaked",
    "streetlamp",
    "streetlamps",
    "streetlights",
    "strode",
    "stumbled",
    "suffocating",
    "sulfurous",
    "supervillain",
    "surged",
    "swirled",
    "swirling",
    "swiveled",
    "sylas",
    "sylvani",
    "sylvans",
    "taehal",
    "tankards",
    "tapestry",
    "taren",
    "tattered",
    "teemed",
    "teetered",
    "tendril",
    "tendrils",
    "tenebrous",
    "terrans",
    "terrifyingly",
    "thalassa",
    "thalen",
    "thalion",
    "thalor",
    "thalos",
    "tharivol",
    "tharos",
    "tharros",
    "theron",
    "thog",
    "thoran",
    "thoren",
    "thorgar",
    "thorgrim",
    "thorne",
    "thorned",
    "thrain",
    "thrax",
    "threadbare",
    "throbbed",
    "throk",
    "throngs",
    "thrum",
    "thrummed",
    "thrumming",
    "thud",
    "thudded",
    "thudding",
    "thunderous",
    "ticked",
    "tightened",
    "tilted",
    "tinged",
    "tingled",
    "tomes",
    "torchlight",
    "torvin",
    "tousled",
    "tousling",
    "towering",
    "townsfolk",
    "transcended",
    "transfixed",
    "treant",
    "trembled",
    "trembling",
    "tremor",
    "trepidation",
    "trifled",
    "trudged",
    "truffula",
    "tugged",
    "twinge",
    "twinkled",
    "twinkling",
    "twitched",
    "unassuming",
    "unbidden",
    "unblinking",
    "unburdened",
    "unclenching",
    "uncurled",
    "underbrush",
    "undercity",
    "undercurrent",
    "understandingly",
    "unease",
    "unfazed",
    "unfurling",
    "unmarred",
    "unmoving",
    "unnerving",
    "unnervingly",
    "unravel",
    "unraveling",
    "unreadable",
    "unremarkable",
    "unseeing",
    "unsettling",
    "unsettlingly",
    "unshaken",
    "unshed",
    "unspoken",
    "unspooled",
    "unwavering",
    "unyielding",
    "uthgar",
    "uuwu",
    "vael",
    "valerius",
    "valoria",
    "valtor",
    "varek",
    "varen",
    "varyn",
    "vastness",
    "venon",
    "verdant",
    "veridia",
    "veridian",
    "veridium",
    "verran",
    "vespera",
    "vexar",
    "veyl",
    "veyn",
    "veyne",
    "veyra",
    "veyth",
    "vial",
    "vibrant",
    "vibrated",
    "viewport",
    "viewscreen",
    "volkov",
    "vorath",
    "vorlag",
    "vorn",
    "vorne",
    "voryn",
    "voss",
    "vrook",
    "vrykali",
    "vrynn",
    "wafted",
    "wailed",
    "warily",
    "wariness",
    "warred",
    "wavered",
    "wavering",
    "weariness",
    "weathered",
    "welled",
    "wheezed",
    "whimpered",
    "whir",
    "whirled",
    "whirred",
    "whirring",
    "whirs",
    "whisper",
    "whispered",
    "whispering",
    "whispers",
    "whisperwind",
    "whisperwood",
    "whiterun",
    "widened",
    "winced",
    "wincing",
    "windowpane",
    "windowpanes",
    "wizened",
    "wojek",
    "woodsmoke",
    "writhe",
    "writhed",
    "writingprompts",
    "xandros",
    "xanthean",
    "xantheans",
    "xaphan",
    "xaren",
    "xarpti",
    "xavius",
    "xendari",
    "xenobiologist",
    "xenobiology",
    "xenolinguist",
    "xenos",
    "xeridian",
    "xeridians",
    "xhk'kht",
    "xyla",
    "xylar",
    "xylara",
    "xylia",
    "xylo",
    "xylons",
    "xylophia",
    "xylos",
    "xylosian",
    "xylosians",
    "xylossian",
    "xylossians",
    "xyloth",
    "xylothian",
    "xylothians",
    "xylox",
    "xyra",
    "y'lgoth",
    "yawned",
    "yearned",
    "yellowed",
    "yelped",
    "yowled",
    "zafir",
    "zalrex",
    "zarek",
    "zarthus",
    "zephyr",
    "zephyra",
    "zephyria",
    "zephyrian",
    "zephyrians",
    "zephyrion",
    "zephyros",
    "zephyrus",
    "zetans",
    "zha'thik",
    "zhra'gha",
    "zorath",
    "zorax",
    "zoraxians",
    "zorgon",
    "zorp",
    "zorvath",
    "zorvathian",
    "zorvathians",
    "zydonian",
    "zydonians",
    "zyla",
    "zylar",
    "zylara",
    "zyloth",
    "zylth",
    "zyn",
    "zyn'thari",
    "zyn'thra",
    "zyra",
    "zz'glorg",
    "said voice",
    "deep breath",
    "voice barely",
    "could help",
    "asked voice",
    "barely whisper",
    "heart pounding",
    "took deep",
    "felt like",
    "mind racing",
    "could feel",
    "find way",
    "air thick",
    "voice low",
    "eyes wide",
    "stepped forward",
    "shook head",
    "voice steady",
    "made way",
    "could see",
    "eyes widened",
    "help feel",
    "first time",
    "brow furrowed",
    "voice trembling",
    "pounding chest",
    "something else",
    "closed eyes",
    "eyes filled",
    "felt surge",
    "eyes narrowed",
    "shake feeling",
    "dimly lit",
    "whispered voice",
    "casting long",
    "felt sense",
    "felt strange",
    "mind raced",
    "barely audible",
    "could shake",
    "heart racing",
    "eyes fixed",
    "heart raced",
    "world around",
    "young woman",
    "eyes scanning",
    "knew would",
    "feel sense",
    "long shadows",
    "sense unease",
    "would never",
    "thick scent",
    "sense purpose",
    "run spine",
    "shadows across",
    "looked around",
    "replied voice",
    "one day",
    "voice laced",
    "leaned forward",
    "fell silent",
    "voice filled",
    "knew could",
    "across face",
    "voice echoing",
    "stark contrast",
    "make sense",
    "lay ahead",
    "help wonder",
    "young man",
    "looked eyes",
    "took step",
    "hung air",
    "raised hand",
    "opened eyes",
    "sun dipped",
    "leaned back",
    "one thing",
    "let go",
    "gaze fixed",
    "raised eyebrow",
    "living room",
    "eyes narrowing",
    "old man",
    "dim light",
    "tilted head",
    "stumbled upon",
    "swallowed hard",
    "flicker something",
    "ready face",
    "deep within",
    "looked like",
    "something far",
    "could hear",
    "never seen",
    "growing sense",
    "smile playing",
    "strange sense",
    "began voice",
    "let us",
    "ever seen",
    "almost imperceptible",
    "constant reminder",
    "dipped horizon",
    "unlike anything",
    "also knew",
    "playing lips",
    "maybe maybe",
    "sound like",
    "felt chill",
    "long time",
    "voice soft",
    "filled air",
    "horizon casting",
    "years ago",
    "voice tinged",
    "fluorescent lights",
    "back chair",
    "glimmer hope",
    "felt weight",
    "beneath feet",
    "voice firm",
    "one one",
    "leaving behind",
    "days turned",
    "heart pounded",
    "around room",
    "would find",
    "mixture fear",
    "caught eye",
    "dark lord",
    "voice dripping",
    "stepped closer",
    "air crackled",
    "fabric reality",
    "caught throat",
    "held breath",
    "face whatever",
    "face etched",
    "figure emerged",
    "nodded eyes",
    "trembling slightly",
    "air around",
    "chill run",
    "spreading across",
    "turned weeks",
    "sense dread",
    "new world",
    "eyes darting",
    "sense peace",
    "mind reeling",
    "eyes gleaming",
    "left behind",
    "something akin",
    "trying make",
    "one would",
    "opened mouth",
    "said eyes",
    "voice echoed",
    "face pale",
    "voice like",
    "way back",
    "could quite",
    "anything ever",
    "like eternity",
    "one could",
    "long since",
    "eyes locked",
    "breath caught",
    "beneath surface",
    "walked away",
    "echoed mind",
    "beacon hope",
    "casting warm",
    "let get",
    "step forward",
    "chapter seven",
    "make sure",
    "carefully constructed",
    "turned face",
    "spoke voice",
    "faces etched",
    "eyes widening",
    "forward eyes",
    "trying keep",
    "cleared throat",
    "could find",
    "turned back",
    "let see",
    "felt shiver",
    "called voice",
    "world outside",
    "next morning",
    "elara felt",
    "felt different",
    "hesitated moment",
    "felt familiar",
    "shiver run",
    "man named",
    "across room",
    "voice barely whisper",
    "took deep breath",
    "could help feel",
    "heart pounding chest",
    "said voice barely",
    "help feel sense",
    "said voice low",
    "voice barely audible",
    "asked voice barely",
    "could shake feeling",
    "casting long shadows",
    "could help wonder",
    "said voice steady",
    "air thick scent",
    "long shadows across",
    "sun dipped horizon",
    "smile playing lips",
    "days turned weeks",
    "chill run spine",
    "felt chill run",
    "whispered voice barely",
    "felt like eternity",
    "shiver run spine",
    "said voice filled",
    "spreading across face",
    "leaned back chair",
    "voice steady despite",
    "unlike anything ever",
    "felt shiver run",
    "taking deep breath",
    "breath caught throat",
    "ready face whatever",
    "heart pounded chest",
    "room fell silent",
    "trying make sense",
    "dipped horizon casting",
    "said voice trembling",
    "something else something",
    "deep breath trying",
    "asked voice trembling",
    "could feel weight",
    "said voice firm",
    "felt strange sense",
    "words hung air",
    "brow furrowed concentration",
    "challenges lay ahead",
    "something else entirely",
    "voice low rumble",
    "sun began set",
    "sent shiver spine",
    "end end end",
    "voice trembling slightly",
    "eyes never leaving",
    "growing sense unease",
    "door creaked open",
    "shake feeling something",
    "air hung thick",
    "heart skipped beat",
    "made way back",
    "took step back",
    "rain continued fall",
    "sun hung low",
    "said voice dripping",
    "said voice soft",
    "casting warm glow",
    "took step forward",
    "eyes wide fear",
    "renewed sense purpose",
    "would find way",
    "trying keep voice",
    "hung low sky",
    "horizon casting long",
    "smile spreading across",
    "leaned forward eyes",
    "anything ever seen",
    "one thing certain",
    "mind racing possibilities",
    "low sky casting",
    "said voice laced",
    "heart hammered ribs",
    "hung heavy air",
    "looked eyes filled",
    "face whatever challenges",
    "took step closer",
    "eyes filled mixture",
    "road ahead would",
    "spread like wildfire",
    "whispered voice trembling",
    "felt sense peace",
    "hung air heavy",
    "air thick tension",
    "newfound sense purpose",
    "flicker something akin",
    "grin spreading across",
    "deep breath stepped",
    "door swung open",
    "knew would never",
    "eyes locked onto",
    "tried make sense",
    "dust motes danced",
    "dimly lit room",
    "small intricately carved",
    "brow furrowed confusion",
    "deep breath steeling",
    "could help notice",
    "one last time",
    "eyes darting around",
    "sent shivers spine",
    "keep voice steady",
    "young woman named",
    "said voice tinged",
    "painting sky hues",
    "eyes wide wonder",
    "nodded mind racing",
    "fingers flying across",
    "whatever challenges lay",
    "figure emerged shadows",
    "mind raced trying",
    "knew road ahead",
    "raised hand silencing",
    "piercing blue eyes",
    "felt strange sensation",
    "turned walked away",
    "said voice calm",
    "small smile playing",
    "felt cold dread",
    "mind racing questions",
    "could find way",
    "spread across face",
    "first time long",
    "ground beneath feet",
    "hung thick scent",
    "sky casting long",
    "mind racing implications",
    "weeks weeks months",
    "asked voice low",
    "chill ran spine",
    "said trying sound",
    "would never forget",
    "gaze sweeping across",
    "asked voice laced",
    "shiver ran spine",
    "turned weeks weeks",
    "spent countless hours",
    "brow furrowed concern",
    "eyes wide mixture",
    "resonated deep within",
    "eyes widened surprise",
    "air thick anticipation",
    "breath catching throat",
    "mind racing tried",
    "deep breath feeling",
    "looked around room",
    "shook head trying",
    "whatever lay ahead",
    "said voice like",
    "replied voice steady",
    "eyes scanning room",
    "felt growing sense",
    "stepped forward voice",
    "never seen anything",
    "stammered voice barely",
    "help feel twinge",
    "knew one thing",
    "stepped forward eyes",
    "smile spread across",
    "maybe maybe could",
    "feel sense unease",
    "seen anything like",
    "knew chilling certainty",
    "growing sense dread",
    "intricately carved wooden",
    "heart heavy weight",
    "words echoed mind",
    "sighed running hand",
    "scent damp earth",
    "air thick smell",
    "said voice smooth",
    "began set casting",
    "blood ran cold",
    "said voice echoing",
    "hand instinctively reaching",
    "sense peace wash",
    "elara said voice",
    "smile tugging corners",
    "said voice tight",
    "could feel power",
    "eyes wide terror",
    "mind already racing",
    "knuckles turning white",
    "felt glimmer hope",
    "made decision would",
    "faint almost imperceptible",
    "eyes widened shock",
    "feel sense pride",
    "tears streaming face",
    "horizon painting sky",
    "casting eerie glow",
    "long could remember",
    "continued fall washing",
]
COMPILED_REGEX_PATTERNS = [re.compile(pattern) for pattern in REGEX_PATTERNS]
